### ISSUE TITLE
JS Script dont found

### ISSUE THREAD

**Issue by s13g3lb4um** [enketo/enketo-express#100]
Hi!!
After a complicated installation enketo webform cant found this file /js/build/enketo-webform-bundle.min.js

In time of installation `npm install --production`  crashes in GRUNT package, i need install this with NPM 

after i run `npm install --production` with basic user  but this fail. Then i run the same command whit sudo and this works fine , but the webapp cant found the file mentioned above

**Comment by MartijnR** [comment]
Sorry to hear this. Something has gone wrong with setting user permissions during install. Did you follow the steps on https://blog.enketo.org/install-enketo-production-ubuntu/?

I don't think there is an issue in the code, so I'll close this for now.
