### ISSUE TITLE
grunt:client-config-file:create not finished before compiling js?

### ISSUE THREAD

**Issue by jnm** [enketo/enketo-express#102]
Originally reported at https://github.com/kobotoolbox/enketo-express/issues/477.

In short: `grunt` must be run twice for themes to work properly.

What seems to happen is:
1. The Grunt task `client-config-file:create` runs before any theme CSS files have been placed in [`public/css`](https://github.com/enketo/enketo-express/blob/478c783b96a26416a0d6c60b60a638bd9ff350db/app/models/config-model.js#L7);
1. The resulting `public/js/build/client-config.js` contains `"themesSupported":[]`;
1. Another Grunt task (that comes later in the `default` sequence) populates `public/css` with the theme files;
1. Rerunning `grunt` at this point makes everything fine: `client-config-file:create` sees the newly-generated themes and outputs `"themesSupported": ["formhub", "grid", "kobo", "plain"]`.

Discussion:
* https://www.flowdock.com/app/kobotoolbox/enketo/threads/1TZmLv2qAygBMP145X59Hh-fZLI
* https://www.flowdock.com/app/kobotoolbox/enketo/threads/yQatM12FbOFglqsdHTFLQAJPzON
* https://community.kobotoolbox.org/t/grid-theme-not-working/3671/31

This became a problem again (for Docker installs) after https://github.com/enketo/enketo-express/pull/87, which removed the second (workaround) `grunt` call from the Docker container startup script.

**Comment by jnm** [comment]
OK, the issue is that `system-sass-variables` calls `require( './app/models/config-model' )`, which puts the theme-less configuration into [`require.cache`](https://nodejs.org/api/modules.html#modules_require_cache):
https://github.com/enketo/enketo-express/blob/478c783b96a26416a0d6c60b60a638bd9ff350db/Gruntfile.js#L214-L219

When `client-config-file:create` runs after the `css` task completes, the `require()` call just uses the cached values, and [`getThemesSupported()`](https://github.com/enketo/enketo-express/blob/478c783b96a26416a0d6c60b60a638bd9ff350db/app/models/config-model.js#L233) doesn't run again.

This doesn't feel too elegant, but it does work:
```diff
diff --git a/Gruntfile.js b/Gruntfile.js
index 2c4a7d5..b977a87 100644
--- a/Gruntfile.js
+++ b/Gruntfile.js
@@ -202,6 +202,9 @@ module.exports = grunt => {
     grunt.registerTask( 'client-config-file', 'Temporary client-config file', task => {
         const CLIENT_CONFIG_PATH = 'public/js/build/client-config.js';
         if ( task === 'create' ) {
+            // https://github.com/enketo/enketo-express/issues/102
+            // The require cache may contain stale configuration from another task. Purge it.
+            delete require.cache[require.resolve( './app/models/config-model' )];
             const config = require( './app/models/config-model' );
             grunt.file.write( CLIENT_CONFIG_PATH, `export default ${JSON.stringify( config.client )};` );
             grunt.log.writeln( `File ${CLIENT_CONFIG_PATH} created` );
```

**Comment by MartijnR** [comment]
Thanks! This sounds like a really great discovery. Will try to reproduce with manual install.

**Comment by MartijnR** [comment]
I'm so glad you discovered this @jnm. Seems like that this has been the situation for a long time. Your proposed fix seems fine. I don't think there is another way without substantially changing how Enketo is configured. So will you submit a PR? (Otherwise, no problem at all for me to just take credit for your fix ;)).

**Comment by MartijnR** [comment]
Alright, I'm taking credit!
