### ISSUE TITLE
Add support for max-pixels in file upload widget

### ISSUE THREAD

**Issue by MartijnR** [enketo/enketo-express#103]
@gushil, now it gets interesting.... Normally updating a widget in enketo-core simply means enketo-core can be updated in enketo-express to propagate the change. However, in this case, since it involves the file-manager (which is overwritten in enketo-express) it is more involved. 

1. update enketo-core and enketo-transformer in enketo-express
2. upload test form to ona or kobotoolbox
3. use api manually to launch form in your local enketo-express, e.g. on localhost:8005/::abcdef
4. make sure updated widget works in online-only form, e.g. on localhost:8005/::abcdef
5. make sure updated widget works in offline-capable form, e.g. on localhost:8005/x/#abcdef

The latter is the hardest because you may be fighting various caches. What I do to ensure the cache is updated after updating js code, is to delete the app manifest entry in the redis cache (the redis item is probably `ma:en_manifest`).

Let me know if you have any questions!

**Comment by theywa** [comment]
@MartijnR, I have some question about some points above :

- I see that you are already updated the version of enketo-core and enketo-transformer in the latest commit in the master branch. This already solved point 1 right or there are some changes that need to be done?
- Point 2, I upload and deploy max-pixels.xlsx on kobotoolbox, but I'm not sure how to use it on my local.
- Point 3, I can load it using /preview like 
![online-error](https://user-images.githubusercontent.com/13865076/62423587-de568b80-b6f4-11e9-811d-b3ad1bd440c4.png)
but I'm not sure which API should I use to get it loaded like e.g. on localhost:8005/::abcdef. Tried using /survey from postman, get the short url with enketo_id but failed to load it. Additional path and query (/formList?formID=) make it inaccessible.

**Comment by MartijnR** [comment]
Hi @theywa,

Yes, step 1 is done.

Using Postman or the terminal is a good way to do this and you seem to have the right /survey endpoint. I think the issue may be with the server url you are using. This is the same for all your forms, and is e.g. something like https://kc.kobotoolbox.org/theywa.

E.g. for my kobotoolbox account (and you can actually try this exact snippet yourself, and load he form) after starting your enketo express app locally (and assuming you kept the default password):

```
curl --user enketorules: -d "server_url=https://kc.kobotoolbox.org/martijnr&form_id=aAmUsEafbqSda45oRYffQ4" http://localhost:8005/api/v2/survey
```

You can also let the apidocs generate the snippet for you, by adding the info in the top left input fields.

**Comment by MartijnR** [comment]
So to clarify the openrosa API a bit. If the "server_url" is _https://kc.kobotoolbox.org/martijnr_, and the form ID is _widgets_, Enketo will:

1. go to server_url + /formList => https://kc.kobotoolbox.org/martijnr/formList
2. find the form with ID "widgets", and see where the form resources can be loaded from

**Comment by theywa** [comment]
Thanks @MartijnR, I get it now.
No problem found during testing, widget woks as expected :
Max-pixel = 100 (online)
![max-pixel-100-online](https://user-images.githubusercontent.com/13865076/62616461-261e2280-b942-11e9-8825-1a6b382f5229.png)
Max-pixel = 1000 (online)
![max-pixel-1k-online](https://user-images.githubusercontent.com/13865076/62616475-359d6b80-b942-11e9-8c54-ba7eac7fd7eb.png)
Max-pixel = 100 (offline)
![max-pixel-100-offline](https://user-images.githubusercontent.com/13865076/62616535-61205600-b942-11e9-954c-e38beadbefed.png)
Max-pixel = 1000 (offline)
![max-pixel-1k-offline](https://user-images.githubusercontent.com/13865076/62616554-6f6e7200-b942-11e9-9d63-d2f7b8f06e3f.png)

**Comment by MartijnR** [comment]
Thanks @theywa, that sounds great. Did you check the submitted images (in KoBoToolbox) as well? I suspect that at least the online-only webform still submits the original images (because the file-manager.js in enketo-core is entirely overwritten in enketo-express). 

For offline-capable webform views (obtained using the /survey/offline endpoint), it will be a little harder to check due to all the caches (as mentioned in the OP).

**Comment by theywa** [comment]
@MartijnR - Now that you mentioned, I just cross-check and found the uploaded images on " Galery " tab, from online and offline mode. 
> I suspect that at least the online-only webform still submits the original images (because the file-manager.js in enketo-core is entirely overwritten in enketo-express).
Yes, that uploaded images had the same size and resolution as the original images.

> For offline-capable webform views (obtained using the /survey/offline endpoint), it will be a little harder to check due to all the caches (as mentioned in the OP).
I already delete "en_manifest" before testing( del "ma:en_manifest", also check using get "ma:en_manifest" and the result is nil ) and uploaded form will send to KoBoToolbox after online again.

Q1: What is the expected response?
Q2: When this "ma:en_manifest" created? After deleting that file on Redis, It looks like not created again(checking on redis-cli monitor)

**Comment by MartijnR** [comment]
Q1: 

When deleting a redis entry, you should see `(integer) 1` if it existed and `integer (0)` if it didn't exist. You can check that it is gone with `keys *` or `keys ma:*`.

Q2: 

It is created/updated when a user loads an offline-capable form while the enketo server is running. E.g. by visiting http://localhost:8005/x/#widgets in the browser.

However, I'd recommend first fixing the online-form. Possibly that touches the same code the offline-capable form uses (not sure), and it's so much nicer to work on an online-only form.

**Comment by theywa** [comment]
@MartijnR - I see, thanks for the answer.
CMIIW, so the uploaded images should be the clone image with pixel no more that max-pixel that set on each form right?
I tried to implement "getCurrentFiles()" method on the file-manager like on enketo-core but still not successfully yet, have some issue with asynchronous method( urlToBlob ) when looping.

**Comment by MartijnR** [comment]
> CMIIW, so the uploaded images should be the clone image with pixel no more that max-pixel that set on each form right?

Yes, that's the feature we're after. It's all about submissions (previews are just nice to have to not give a false impression of submitted image quality).

Sounds like a nice challenge ;). Let me know if you get stuck.

**Comment by theywa** [comment]
@MartijnR - Sorry for the late response, I take 2 days off. It works now, I call "urlToBlob" method on "getFileUrl" method(when it get objectUrl to review the uploaded image) then save it to a global variable that'll be used when submitting. 
Tested on offline and online mode, the file saved on KoBoToolbox are the resized one, not the original. Also tested multiple uploads with the different files in offline mode and no duplicated file saved on KoBoToolbox(got an issue with duplication images on offline mode but it's fixed now).
Here is the [PR](https://github.com/enketo/enketo-express/pull/109)

**Comment by theywa** [comment]
@MartijnR - I found an issue on offline mode using multiple uploads' form so I create a [PR](https://github.com/enketo/enketo-core/pull/652) (it just move the code to promise when resize the image). 
Also when creating PR for enketo-express should I also commit the package.json with latest enketo-core commit?

**Comment by MartijnR** [comment]
Thanks! PR was merged, and I already updated enketo-core in enketo-express (but normally yes, you can include it in your PR)

**Comment by theywa** [comment]
[PR](https://github.com/enketo/enketo-express/pull/109) updated and ready for review.

**Comment by MartijnR** [comment]
On Martijn's machine: http://localhost:8005/::ll3iIZVC and http://localhost:8005/x/#ll3iIZVC
