### ISSUE TITLE
Possibility to add custom submission url

### ISSUE THREAD

**Issue by awemulya** [enketo/enketo-express#111]
e.g.
curl --user abc: "https://enke.to/api/v2/survey/single/once?server_url=https://testserver.com/bob&form_id=widgets&submission_url=https://testserver.com/bob/foo/bar"

default submission url is https://testserver.com/bob/submission which may need to be custom for other new applications using enketo.

**Comment by MartijnR** [comment]
Thanks! There is actually a feature in the XForms (and XLSForms spec) to [define the submission URL in the form format itself](https://github.com/enketo/enketo-express/issues/65). That's the one we're going to implement. Would that meet your requirements?

**Comment by awemulya** [comment]
Thanks for your quick response, but what I need is query params in submission url.
A survey is sent from different  Sites.
https://testserver.com/bob/submission?site=1&country=1
we can sent these query params in creating enketo link.
e.g.
curl --user abc: "https://enke.to/api/v2/survey/single/once?server_url=https://testserver.com/bob&form_id=widgets&submission_url=https://testserver.com/submission?site=1&country=1"

Will this be within scope of enketo?

**Comment by MartijnR** [comment]
ah I see. I don't think this will make it on our roadmap, so you may have to customize in a fork. 

Just wondering if populating the submission XML dynamically with a hidden 'site' and 'country' field using `defaults[]` in the API call would work for you. You'd have to parse the XML submission, but presumably that is happening already anyway.

**Comment by awemulya** [comment]
For now I have  sent as url params `/single/::cRYhn3oD?site_id=1`  and received in submission controller from url `req.headers['referer'];` and I have append this param in `submissionUrl`.  I think this is minumum update for my case.
I will have to merge update onwards which is irritating.

**Comment by MartijnR** [comment]
Oh, actually that provides another idea, already present in Enketo Express! Have a look at: https://enketo.github.io/enketo-express/tutorial-10-configuration.html#query-parameter-to-pass-to-submission

Sorry, I forgot about this. The limitation is that this is only for 1 parameter, but that might work for you by encoding or mapping the value to multiple parameters.

**Comment by awemulya** [comment]
This works perfect for my case. Thank you MartijnR.
