### ISSUE TITLE
Remove IE11 build and therefore IE11 'support'

### ISSUE THREAD

**Issue by MartijnR** [enketo/enketo-express#129]
I think it's time! 

Any objections?

**Comment by lognaturel** [comment]
A+ from Team [ODK Central](https://docs.opendatakit.org/central-intro/). CC @matthew-white @issa-tseng @yanokwa

**Comment by MartijnR** [comment]
* [ ] remove IE11 build from default build task run by `npm install` (and by `grunt`). It will require calling `grunt build-ie11` manually to maintain support.
* [ ] add banner for IE11 users  hat says "Internet Explorer 11 support will end soon. Please switch to a modern browser before then." The 'soon' is not very helpful but it avoids having to worry about deployment dates (and showing "by the end of March 2020" some time in 2021 when somebody runs an old version.
* [ ] remove ie11 build packages and tasks entirely in April 2020
