### ISSUE TITLE
Blocking GUI issue - "Save as Draft" checkbox

### ISSUE THREAD

**Issue by NoelCartONG** [enketo/enketo-express#131]
Over the past couple of years I have faced a recurring problem in the otherwise fantastic functionality of the Enketo system. Recently I had an opportunity to troubleshoot why so many new users were reporting that their data was not being submitted and was surprised to discover that connectivity or technical issues where not occurring in the majority of cases.

The problem was often that while the text beside the checkbox says "Save as draft", after completing a long form most users intuitively think this final check box will be to say that the form is done and a significant percentage don't read these final words. This is especially important as for language reasons the word "draft" is not always immediately understood and users are sometimes familiar with ODK Collect which has a final check box with the opposite meaning.

In many of these cases the user assumes that their data has been submitted and therefore with every new form additional training is necessary so that users remember to check the zero in the top left of the screen before closing their browser tab. While this is not a complicated thing to do, this training only reduces and doesn't eliminate the problem.

Some very small changes to the GUI would be much more effective.   Personally I think the checkbox should be removed and replaced with two buttons "Submit Data" and "Save Draft".  Two buttons would be much more intuitive than a check box and one button that changes meaning while remaining the same colour.  Alternatively the "Save Draft" and "Submit Data" buttons could simply be different colours in order to better highlight that the functionality behind the button has indeed changed. Either way the text in the "Save as Draft" dialog box which pops up needs to changes to better explain what is happening as for many users the distinction between "saving" data and "submitting" data is lost. There are arguments for and against the use of symbols to help differentiate.

While its unfortunate that this small GUI design issue is causing the reliability of the system to be questioned, I hope that the fact that the solution is superficial means that it will be possible to rectify the issue fairly soon. Below I have attached a rough mock-up of one potential solution but there may be other designs which would work better.

![enketomod1](https://user-images.githubusercontent.com/61494702/75331204-978fd500-5882-11ea-9067-35c0f044a032.png)

**Comment by MartijnR** [comment]
Thanks very much for this feedback. It makes sense to me. 

Implementing this would take some time, as the footer has lots of possible UI elements (but we do already have a multi-button interface in OpenClinica's fork, so we may be able to use that work).

Letting this simmer a bit and would like to invite others to chime in.

**Comment by NoelCartONG** [comment]
Thanks very much for the response. The feedback is very much appreciated.  While 2 buttons would be ideal, I understand that this may need to wait for some significant changes. Can I ask if you have any thoughts on a possible one-button solution even as an interim measure?

Below I have attached a quick mock-up of a one button solution. In French the difference in the Save and Submit buttons is more obvious as the length of the word Sauvegarder causes the size of the button to change and so you notice that there is a connection between the Save check box and the button.  If it would be possible for the Save button to appear differently from the submit button and to use wording which is more universal, then that might already help. Even removing the "check mark" from the save button could help differentiate from the submit button. 

As I run training sessions on ODK based tools most months, I would be willing to conduct a test with groups of new users to verify if the change has been effective. 


![enketo_mod4](https://user-images.githubusercontent.com/61494702/75679305-aa921300-5c8f-11ea-8e43-e802d868af3b.png)

**Comment by MartijnR** [comment]
Thanks Noel, I think we can do the right thing right away with 2 buttons, as it makes sense to me and avoids having to temporarily update translation strings (resulting in missing translations for quite a while). Just want to give others, especially KoBoToolbox folks some opportunity to comment (pinging @tinok, @jnm).

**Comment by tinok** [comment]
I think this is a good and overdue UI improvement. Thanks for starting this issue @NoelCartONG. I agree with @MartijnR that the two buttons is the right next step, the intermediary option would be hella confusing to users. 

I am looking for some indication on the second button to tell users some crucial information. Maybe a little "Learn more" link below which opens up a modal or new tab? This would be the text I'd feature there: 
* Your draft submission is stored only **within the current browser**. You can close this browser without losing the draft data. 
* You can store multiple drafts of this form.
* You can access it in the future by reopening this page and clicking on the offline drawer [include picture since people don't notice this button usually]. If you have multiple drafts they will all be listed there. 
* Important: If you clear your browser cache all your draft submissions will be permanently deleted as well.

**Comment by tinok** [comment]
CC @magicznyleszek for opinions on the new button to replace the checkbox for offline forms.

**Comment by magicznyleszek** [comment]
I agree that two buttons are superior to checkbox :)

**Comment by MartijnR** [comment]
Thanks! I'll try to squeeze that change into the next version.

**Comment by jnm** [comment]
This would be a great improvement! I do think the existing check box icon for the submit button is superior to the one proposed: it implies finality. I'd also advocate for the pencil, as already used in the Enketo UI, to be the icon for saving a draft vs. the (sadly) less-and-less familiar floppy disk.
![image](https://user-images.githubusercontent.com/2085013/75800028-f5229680-5d46-11ea-9c3b-266335896e02.png) ![image](https://user-images.githubusercontent.com/2085013/75800038-f6ec5a00-5d46-11ea-9184-8266f1fed9db.png)
If new icons are used, please consider updating the rest of the UI to match.

The above was just a quick hack using the browser's inspector and not intended to argue against having the buttons be different colors, which would be helpful for clarity. I'm not sure how to balance that distinctiveness against having the draft button appear to be disabled, though.

**Comment by MartijnR** [comment]
Thanks! I agree with maintaining the existing check icon, and the pencil icon. 

Will think about button colors. In any case, I think the submit button should be on the right, if we consider it the default/main action.

**Comment by MartijnR** [comment]
* [ ] check on small screen
* [ ] check with logout link
* [ ] check with back/next/end/start pages-mode buttons

**Comment by MartijnR** [comment]
I deployed this on odk.enke.to. The hardest is to get the wording of the information dialog right, and that's the most important (because changing translation strings later on is something we want to avoid, especially long strings).

<img width="683" alt="Screen Shot 2020-03-03 at 2 05 54 PM" src="https://user-images.githubusercontent.com/627350/75819595-32dbeb00-5d58-11ea-886a-bb68a2d10973.png">

Please have a look at https://odk.enke.to/x/#YYY5, and let me know if you'd like to change anything, in particular text strings, before I merge this.

* [ ] switch odk.enketo.to back to the `master` branch

**Comment by NoelCartONG** [comment]
Hi, just to confirm that for me the text works very well as is.  Even if not everyone is familiar with terms such as browser and cache, its not a problem as the title already makes clear that the record has not yet been submitted.  Whether the user is trying to submit the record immediately or store it for later, all necessary information is included in a clear way so I don't have anything to add before its merged.  I am however happy to work with colleagues on translations into different native languages if there is a way to contribute to that.  French, Spanish and Arabic should at least be possible.

Its been interesting for me to learn a bit about GUI design considerations from the discussion as well so thank you all for your contributions to the final solution.

**Comment by MartijnR** [comment]
Thanks @NoelCartONG. It would be great to get translation support from CartONG people, especially for Arabic (as universal as possible, since we don't support dialects). For Enketo Express a translator can request to be added to a language here: https://www.transifex.com/enketo/enketo-express/languages/. Once they've been added they should get a message via Transifex when source text (English) is updated. We will keep track of when a translator has completed all missing/updated strings for a language.

**Comment by NoelCartONG** [comment]
Thanks for the link!  Apologies I edited my comment slightly without realising you had already responded but its absolutely not priority at all.  I will ask around tomorrow and see what languages are possible, it may be that Arabic is not but another language will be.

**Comment by NoelCartONG** [comment]
French, Spanish and Arabic translations added, each one done with at least one native speaker and Arabic as universal as possible.  While travel restrictions and cancelled events are somewhat reducing the opportunities, if I come across people who would be happy to translate any texts in other languages, I will encourage that for sure.  Thanks so much for taking this forward so quickly, looking forward to seeing the new GUI when released on Kobo.

**Comment by MartijnR** [comment]
Excellent. Thanks so much! I think the updated translations will be added today, and a new version released.

**Comment by MartijnR** [comment]
If you'd like me to add the names of the translators [here](https://github.com/enketo/enketo-express#translation), please let me know what they are.

**Comment by NoelCartONG** [comment]
Sure, Arabic = Nancy Shapsough, French = Noel O'Boyle, Spanish = Miguel Moreno.  Much appreciated.
