### ISSUE TITLE
TypeError in Edge

### ISSUE THREAD

**Issue by danbjoseph** [enketo/enketo-express#138]
I think this is an Enketo issue, despite the error message instructions for reporting to the kobotoolkbox email?

With this form: [comm of practice survey.xlsx](https://github.com/enketo/enketo-express/files/4432284/comm.of.practice.survey.xlsx)
On https://kobo.humanitarianresponse.info/

This error was seen by a user when trying to fill out the survey using Edge. Works fine in Chrome and Firefox. `TypeError: Object doesn't support property or method 'append'`

![image001](https://user-images.githubusercontent.com/4806884/78459544-bfdfd000-7687-11ea-889b-9d08d9bc8da5.png)

**Comment by MartijnR** [comment]
Hey @danbjoseph. Thanks for this. I'm sorry, somehow I totally overlooked this report. Will check it out asap.

**Comment by MartijnR** [comment]
enketo-core: http://192.168.68.115:8005/?xform=https://xlsform.getodk.org/downloads/jzy8p7l1/comm.of.practice.survey.xml

**Comment by MartijnR** [comment]
I am giving up trying to run a Windows VM for now. If any Windows user is able to upload the form above to https://getodk/xlsform/ and see if there is a loading error in Edge in the Enketo preview, that would be much appreciated. That server runs a more modern version of Enketo Express.

**Comment by jnm** [comment]
It looks okay to me using Edge 81 via BrowserStack:
![image](https://user-images.githubusercontent.com/2085013/80842937-e3d3fa00-8bd0-11ea-89f7-29794a260815.png)

**Comment by MartijnR** [comment]
Thank you! Assuming it's fixed then.
