### ISSUE TITLE
make Enketo ID length configurable

### ISSUE THREAD

**Issue by MartijnR** [enketo/enketo-express#146]
up to 64 chars? (just for testing purposes, it would be good to set a limit)
make sure to test this with encrypted IDs

**Comment by lognaturel** [comment]
I think people want their URLs to look like the obfuscated URLs of services they're familiar with. For example, I'm counting ~35 chars with GDrive (seems variable?). 64 sounds great for the upper limit!

**Comment by MartijnR** [comment]
* [ ] fix all tests that rely on a fixed ID length

**Comment by MartijnR** [comment]
@lognaturel, this is ready for testing in latest master (release to follow shortly, I think). The docs will be updated when the release is made, but it's just an `"id length" : 32` (4-64)  setting in config.json (root).

**Comment by lognaturel** [comment]
This is amazing. 🔥🔥🔥

**Comment by MartijnR** [comment]
@lognaturel, I created a somewhat serious issue with this feature. Easiest fix would be to make the upper limit 31 characters. Is this feature in use already, and if so what ID length that was configured?

**Comment by lognaturel** [comment]
Oh no, sorry! We have not updated the production server yet. I was going to go with 32 but 31 is no problem. I imagine that would be long enough for most folks.

**Comment by MartijnR** [comment]
That's great news. Thanks!
