### ISSUE TITLE
Enketo version 2.3.2, Microsoft Edge 44.17763.831.0, spread operator not supported

### ISSUE THREAD

**Issue by ktmatzdorf** [enketo/enketo-express#169]
with the newer chromium based edge browser the object spread operator is supported and enketo is working smoothly.
For versions 18 and older you get an error:
SCRIPT1028: SCRIPT1028: Expected identifier, string or number

@MartijnR is there a way to fix it?

**Comment by MartijnR** [comment]
Thank you!

If anybody can figure out where the spread operator for objects is used, and if it's not an external dependency, we'll fix it. If it's in Enketo's code, I don't expect it to be used more than once or twice.

I no longer have the patience for running a windows VM, so any help is appreciated.

**Comment by neurolabs** [comment]
In minified code, the surroundings of the usage are:

`Ve=(e,t,n,i)=>("function"==typeof n&&(i=n,n=void 0),i=i||(()=>{}),Oe?((e,t,n,i)=>{e.queryStringParams&&(t=ze(t,e.queryStringParams));const r={...e.customHeaders||{}};n&&(r["Content-Type"]="application/json"),Oe(t,{method:n?"POST":"GET",body:n?e.stringify(n):void 0,headers:r,..."function"==typeof e.requestOptions?e.requestOptions(n):e.requestOptions}).then(e=>{if(!e.ok)return i`

that's two occurences in one snippet. In total, I can find 51 occurences in the minified enketo-webform-bundle.min.js.

**Comment by neurolabs** [comment]
Maybe the minification optimizes in some of the spread syntax?

**Comment by neurolabs** [comment]
How do you feel about including babel transpiling in your build, so you can continue using the object spread syntax while fully supporting older browsers?

**Comment by MartijnR** [comment]
Thanks @neurolabs. I want to avoid Babel, as I'm so glad we finally got rid of it recently after dropping IE11. Yes, it's used a lot for Arrays in our code, but probably only once or twice for an object.

Running Enketo using `grunt develop` would show where it is (without minification). Good point about minification possibly adding more occurrences. I guess it is possible (and we can probably avoid that if so).

**Comment by neurolabs** [comment]
@MartijnR it seems that the object spread syntax is also used in externals, e.g. i18next-http-backend. I don't see a way around this other than babel, do you?

**Comment by MartijnR** [comment]
Thanks for investigating @neurolabs!

A PR for a babel build targeting Edge (Legacy) 18 only would be welcome. Though I'd be fine with not supporting Edge Legacy too since on https://enke.to Edge users on version <=18 constitute a minuscule 0.25% of total users. 

@jnm, is this concerning to you? What are your numbers?

@pbowen-oc, are you experiencing problems running your form views on Edge Legacy?

**Comment by neurolabs** [comment]
@ktmatzdorf created a pull request reintroducing babel https://github.com/enketo/enketo-express/pull/172

**Comment by pbowen-oc** [comment]
@MartijnR - We haven't had reports of issues specific to Edge Legacy. Based on the discussion above, I'm not sure what the implications of this issue would be for our users, so I'm not not sure how relevant it would be for our use case.

It looks like about 5% of our recent traffic is from Edge Legacy. Eyeballing those further, it looks like almost all are on version 18.

**Comment by neurolabs** [comment]
@pbowen-oc did you test yourself with Edge Legacy? If not, could you provide a URL for testing (I have the Windows Development VM installed and can do testing).

**Comment by pbowen-oc** [comment]
@neurolabs - I did test with Edge Legacy myself. I did not observe any issues. I'm not sure what cases would be affected by the issue, so not I don't know what testing would be needed.

**Comment by MartijnR** [comment]
This commit also belongs to this issue: https://github.com/enketo/enketo-express/commit/29ce62c69d209a8a63b1c7660579e0b73eb6ee10

Looks like it's working => https://odk.enke.to/YYY5.  Thank you!
