### ISSUE TITLE
Is it possible to integrate other base layers such as Google Satellite, Bing Imagery, in addition to OSM in Submission Page Form which have location question type?

### ISSUE THREAD

**Issue by santoshkhatrii** [enketo/enketo-express#192]
**Is your feature request related to a problem? Please describe.**
We need to plot markers or draw polygons over satellite images.

**Describe the solution you'd like**
A simple icon to switch base layer as in other map user interfaces. Mainly we need satellite image switch.

**Describe alternatives you've considered**
Custom code in JavaScript for map base layer.

**Additional context**
Currently the map interface in the form looks like below:
[Screen Shot 2020-07-30 at 5 36 07 PM](https://user-images.githubusercontent.com/20319653/88920385-79dcf680-d28c-11ea-9ef4-c66eb78a4ae1.png)

**Comment by awemulya** [comment]
@MartijnR It would be really helpful, if we can switch base layers Other than osm.

**Comment by geomatupen** [comment]
I also want similar feature where I would like to draw features over satellite imageries rather than osm streets. Is there any way we can add ZXY tiles or any other tiles as base layer for this map?

**Comment by MartijnR** [comment]
Hi all, The person/company that installs Enketo can add as many MapBox/Leaflet/Google layers as they want. So am not sure if your request should be aimed here or elsewhere. We only run one server ourselves and have set 3 map layers (see https://enke.to/widgets).

Here is the configuration guidance: https://enketo.github.io/enketo-express/tutorial-10-configure.html#maps

Please re-open if I misunderstood and you actually are looking for a new feature instead.

**Comment by MartijnR** [comment]
P.S. you can open a question to any default baselayer that is installed by adding the layer name as an appearance e.g. "satellite".

**Comment by awemulya** [comment]
@MartijnR Thank you for your response. I got it.

**Comment by santoshkhatrii** [comment]
Hi @MartijnR,
Thank you so much for your quick response and the configuration guidance link too.
![Screen Shot 2020-07-31 at 9 43 56 AM](https://user-images.githubusercontent.com/20319653/88998723-6a07f580-d312-11ea-8167-07ef21fe463d.png)

That was exactly what we needed to add other base layers in our enketo server.
