### ISSUE TITLE
Error handling after load error

### ISSUE THREAD

**Issue by matthew-white** [enketo/enketo-express#202]
I was looking at #201 and noticed that there are actually two error messages shown in the console. One is described by #201, but the other seems to be related to how a load error is handled:

> Uncaught (in promise) TypeError: Cannot read property 'languages' of undefined

This message isn't shown to the user outside the console: only the messages from #201 are shown outside the console. However, this `TypeError` seems to stem from a different part of the code from #201 (enketo-express instead of enketo-core), so I thought I'd file a second issue.

The `TypeError` seems to be thrown by the last line here:

https://github.com/enketo/enketo-express/blob/b8694b67fd1731d43a7bc2cf74bf56cedd321824/public/js/src/enketo-webform-view.js#L86-L96

I think what's happening is that even after a load error, `controller.init()` returns a fulfilled promise, but one in which `form` is `undefined`. I think Enketo Express could prevent this message from appearing in the console by:

- Checking in the `then()` callback here whether `form` exists
- Alternatively, having the `catch()` callback in `controller.init()` rethrow the error, then adding a `catch()` callback here

The text of the error message above is from Chrome. The text is slightly different in other browsers:

- Firefox: Uncaught (in promise) TypeError: t is undefined
- Safari: Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 't.languages')

CC @lognaturel

**Comment by MartijnR** [comment]
Thank you!

**Comment by lognaturel** [comment]
I've attempted to move this issue to https://github.com/enketo/enketo a number of times over the past couple of days and it always fails. Now transfer attempts create ghost issues like https://github.com/enketo/enketo/issues/1284 I don't think it's very important so this issue will stay here!
