### ISSUE TITLE
Remove Babel?

### ISSUE THREAD

**Issue by MartijnR** [enketo/enketo-express#204]
Babel was only meant to solve a temporary issue while Edge 18 is still in use (which technically we [do not support](https://enketo.org/faq/#browsers)). It likely is the cause of increased memory usage during build. Thankfully for us, Microsoft has been aggressive in getting people off the old Edge.

@jnm, @ivermac, @lognaturel, @matthew-white, do you see any significant Edge 18 (or less) usage?

**Comment by MartijnR** [comment]
enke.to: 9% of 3.87% = 0.33% so no reason to keep this 

The page will load with a big ugly error message, so there is little risk.

**Comment by MartijnR** [comment]
On one incredibly busy OCHA server run by KoBo (the only one I have access to analytics for):  45% of 1.87% = 0.84%

**Comment by MartijnR** [comment]
@jnm, @tinok, if those OCHA numbers are worrying, we could also have an additional custom build `build-edge-old` task to support these old Edge users and default to "latest browser version supported only".

**Comment by lognaturel** [comment]
Central doesn't support non-Chromium Edge so no need for `babel` from our end!

**Comment by jnm** [comment]
I wouldn't bother with `build-edge-old`, but thanks for consulting us :heart:

**Comment by MartijnR** [comment]
Perfect. Thanks. Let's give Ona a day to chime in, and then go ahead with dropping Edge 18 support.

**Comment by tinok** [comment]
@MartijnR What will be the behavior for Edge 18 users after this change? Do users see the unsupported-browser message? Or is it just a gradual degradation of CSS etc? I _am_ worried about the 0.84% of users on the OCHA server.

**Comment by jnm** [comment]
> What will be the behavior for Edge 18 users after this change?

Martijn wrote "big ugly error message", which I took to mean this:
![image](https://user-images.githubusercontent.com/2085013/91189188-26f63380-e6c0-11ea-8005-c53cc6c6c85f.png)

> Maybe we could temporarily show a message to Edge 18 users on EE to let them know that support for this browser is going to be dropped before deploying this commit

I do not support this, sorry.

**Comment by MartijnR** [comment]
It would be a modal dialog with a loading error and a warning not to use this for data collection. I'll confirm this. The "ugliness" is in the fact that it's a Javascript exception error message that will be meaningless to most users.

We could also sniff Edge Legacy and redirect to `/modern-browsers` as @jnm had understood (as we do with IE11, I think)

**Comment by ivermac** [comment]
Hey @MartijnR, removing babel should be fine on Ona's end as well

**Comment by MartijnR** [comment]
It looks like the unsupported object spread syntax (that required babel transpilation) is no longer present in the current Enketo (i.e. its libraries). So we won't lose support for Edge Legacy (for now), at least not for EdgeHTML 18.177763.

**Comment by lognaturel** [comment]
> So we won't lose support for Edge Legacy (for now)

A true "have your cake and eat it too" moment! 👏
