### ISSUE TITLE
sessionid cookies is removed

### ISSUE THREAD

**Issue by jdugh** [enketo/enketo-express#206]
**Describe the bug**
On my Enketo own instance, 2.3.10, when I submit a form, Enketo remove my sessionid cookies (for all the kobotoolbox instance)

**Browser and OS (please complete the following information):**
 - OS: debian 9
 - Browser : chrome

I have a own instance of kpi, kobocat and enketo, without docker.
I don't find where this removed is made.
Thank's for your help

**Comment by MartijnR** [comment]
@jdugh where do you see that a cookie has been removed (on what page)? Am pretty sure Enketo doesn't remove cookies.

**Comment by jdugh** [comment]
@MartijnR  thank's for your quickly answer.
In the dev' console of Chrome. My sessionid is present (create by kpi), and at the end of submiting (on enketo), the sessionid was removed. So disconnect to kpi/kobocat
I Am pretty sure too, enketo doesn't remove cookies. But I don't understand how it can be removed.
I will recheck my conf and, if necessary reinstall all plateforme from the source.

**Comment by MartijnR** [comment]
> and at the end of submiting (on enketo), the sessionid was removed

Are you still on an Enketo webform page when you observe this? Or have you been redirected to another page by then?

**Comment by jdugh** [comment]
I found my problem.
my apologies, it's my fault.
I changed SESSION_REDIS in kpi settings and didn't apply the same change in kobocat settings.
So it's not at all an Enketo problem, but a configuration problem on my part.
Sorry and thanks for the whole Kobo solution!

**Comment by MartijnR** [comment]
Thanks for reporting back. Good luck!
