### ISSUE TITLE
How to prefill a form with data

### ISSUE THREAD

**Issue by sucrecacao** [enketo/enketo-express#214]
Hello, 

I'm using forms inside another app. The app holds data that is needed for the form. 

I there a way to download a form and to dynamically prefill some of the fields with data from my app storage ? 

For example, my app already know the name of the user. Is it possible to download a form and to automatically fill up the 'name' field with the user's name I hold in my app ? 

Thanks

**Comment by sucrecacao** [comment]
Solution might be here: https://github.com/kobotoolbox/enketo-express/issues/1093 
Weird that I didn't found it on search engine

**Comment by sucrecacao** [comment]
@MartijnR  Could you please explain what you mean by

>  For offline-capable views, I'd prefer to use a 3rd option: external data (XML or CSV) and then use a calculation to populate questions. Enketo has been designed to facilitate serving different external data documents to different users (most feasibly by using the existing authentication).

Also could you give a few pointers on what would the path to achieve this feature with offline survey ?

**Comment by MartijnR** [comment]
Hi @sucrecacao,

Are you using enketo-core inside your custom app?  It seems like using enketo-express would be unusual.

> Also could you give a few pointers on what would the path to achieve this feature with offline survey ?

Have a look at the pyxform XForm output when you use a calculation with pulldata. It provides an `<instance>` with a `src` attribute. Also, of course, looking at the XForms spec is helpful: https://getodk.github.io/xforms-spec/#secondary-instances---external
