### ISSUE TITLE
Media files with spaces in their filename do not load

### ISSUE THREAD

**Issue by noliveleger** [enketo/enketo-express#218]
With a XLSForm like this one

name | type | label | media::image
-- | -- | -- | --
hey | note | some image | image with spaces in the name.jpg
nspacio | note | nospace | nospace.jpg

`nospace.jpg` loads but `image with spaces in the name.jpg` does **not**

**Comment by lognaturel** [comment]
Same issue affects submissions that are open for viewing/editing. There's no request made for the image -- something goes wrong before.

**Comment by eyelidlessness** [comment]
@joshuaberetta I meant to mention yesterday, but I'm looking into this now too. I think it's likely the appropriate fix for this is in [enketo-transformer](https://github.com/enketo/enketo-transformer). I've also identified two similar but likely unrelated bugs in enketo-express, which I'll file separately.
