### ISSUE TITLE
Referencing a url in a note question (question label) not working!

### ISSUE THREAD

**Issue by Kalyan-Lama** [enketo/enketo-express#221]
**Describe the bug**
When you reference a question with url in a note question (question label) as shown in the image below ... 
![Image 0](https://user-images.githubusercontent.com/50188479/102074473-f7b13100-3e2c-11eb-8d9d-a7c223504ec4.png)
it does not work in `Enketo`. The same however works with `Collect android app`.

**Steps To Reproduce**

1. Upload the sample xlsform shared below:
[URL Test.xlsx](https://github.com/enketo/enketo-express/files/5688374/URL.Test.xlsx)
2. Deploy.
3. Try to collect data through `Enekto` and you should see the following:
![Image 1](https://user-images.githubusercontent.com/50188479/102074804-6d1d0180-3e2d-11eb-91e4-805b5f39f944.png)
4. Similarly, try to collect data through `Collect android app` and you should be able to see the `url` link as it should see:
![Image 2](https://user-images.githubusercontent.com/50188479/102075642-a609a600-3e2e-11eb-9485-1c39b7ca6e5e.jpg)

**Expected behavior**
The `url` link should also be able to display as it displays in `Collect android app`.

**Browser and OS (please complete the following information):**
 - OS: `Windows 10`- PC, `Android 10`- Android device
 - Browser [`Chrome`]

**Additional context**
**Link to the community forum:** https://community.kobotoolbox.org/t/link-to-url-from-pulled-data/14494/5

**Comment by MartijnR** [comment]
Thanks @Kalyan-Lama, 

Dynamic href attributes as part of labels and hints are not supported, and not planned to be supported. We do support the 'url' appearance, and I believe that one could be dynamic.

**Comment by jborruel** [comment]
Thanks @MartijnR

I have read your comments, but I don't think that the "url" appearance is dynamic, as per the tests I have done recently...

I have tried different solutions, and I have only succeeded while writing a static text. You can check the cases below, as I haven't been able to make any of them work:

![image](https://user-images.githubusercontent.com/36068602/102188264-5fab5a00-3eb5-11eb-895b-8e0a862969a9.png)


![image](https://user-images.githubusercontent.com/36068602/102188298-6934c200-3eb5-11eb-80f4-b99ef8624ab9.png)

(particularly the one with the calculated field, highlighted in red)

Regards

**Comment by MartijnR** [comment]
Hi @jborruel,

With the URL widget it's the value that's turned into a link. I just confirmed it is indeed dynamic and I remember now that this is really what makes this a useful widget and why we added it. See this example form: https://docs.google.com/spreadsheets/d/1rpZxd2Ip6duswxDvcDwqco0cku1GXnF00eGLTuO8EVw/edit?usp=sharing

You can e.g. concat() to create URL variations using calculations.
