### ISSUE TITLE
Form with 'or or' in relevance condition used to load but fails with error since Jan 2021

### ISSUE THREAD

**Issue by ghost** [enketo/enketo-express#224]
We have a larger than usual form designed and tested specifically for use with Enketo but it looks like something changed in the last few weeks and it is no longer possible to open the form.  The issue seems to be the number of **questions** in the form rather than the number of **choices** as while there are a lot of choice lists, each one is short. The below error appears on opening the form (there are no errors on uploading or deploying the form).

In order to check that the number of questions in the form was the likely problem, we reduced the number of lines on the survey sheet of the XLSform from 3000 to 2000. As the form worked well on Enketo until December and hasn't been changed in any way, we are wondering if there have been changes made which may have lead to longer forms such as this one no longer working.  While it is a long form, it has a very simple structure with no repeat groups, choice filters or calculations of any sort and so it actually loaded quite quickly when opened.

Please let us know if any relevant changes have since taken place and if these errors are likely to be only temporary. We can share both the full version and the "shortened" version of the form causing the error if that's useful but would prefer to send them in a non public manner as they have been created on behalf of a partner organisation.  The form is not currently live although there may be other live forms which will hit the same problem in the next few weeks and the aim is to run a pilot as soon as possible.

![Screenshot 2021-01-04 at 16 09 52](https://user-images.githubusercontent.com/61494702/103558852-93c2db00-4eb5-11eb-9c8f-1fceaed17f95.png)

**Comment by MartijnR** [comment]
Thanks for reporting @NoelCartONG! There is a bug in version 2.6.0. While we're fixing this, servers should downgrade to 2.5.6. I don't remember if you're using your own server, but I've downgraded enke.to this morning and have discussed with KoBo to do the same (which I think will be done).

bug ref: https://github.com/enketo/openrosa-xpath-evaluator/issues/67 (the fix will be in 2.6.1, but it may take a while).

**Comment by MartijnR** [comment]
Actually, @NoelCartONG, if you can identify it, could you perhaps paste the XLSForm formula that is causing this error (or send the whole form)? It seems the bug may not be in an `if()` function in your case, which is interesting.

Also, I happened to notice there is a double `or or` near the last line. I suspect that may be an error in the formula (that perhaps previously was silently swallowed), but really is an error. If so, definitely worth checking if that resolves it.

**Comment by MartijnR** [comment]
* [ ] Martijn to check http://localhost:8005/XfnxYcR0KWApbMfaK96UMoYYNU2XX0i (form 10103 on Centro) after a fix has been implemented.

**Comment by NoelCartONG** [comment]
Thanks Martin for your quick and very helpful response.  The form did indeed contain the double "or or" and once removed the form works.  For the record, since you did a roll back yesterday related to the other issue you mentioned which it seems we were not a case of, the old form works again despite the error included.  I am assuming this is because while the extra OR fails, the fact that it's an OR means that if another part of the conditional statement returns TRUE, then the calculation as a whole still returns a relevant result.

However it seems the fact that it's not flagged as an error during the XLS/XML conversion process should be changed as I am not sure how all combinations of empty doubles would behave (OR OR, AND AND, AND OR, NOT(OR OR), NOT(AND AND), NOT(AND OR) etc.) and it seems like there is little benefit to not classing all of these as errors.

It seems that the new Enketo version has a more robust error checking process on this aspect.  Would you advise that this issue be closed on the Enketo github and opened on the ODK forum instead?

**Comment by MartijnR** [comment]
I double-checked if a double "or or" is allowed in XPath and found it isn't. (I checked `document.evaluate('true() or or 1', document, null, 3)` in a browser console which uses the built-in native XPath evaluator). So I think the fact that the currently deployed older Enketo seems to not choke on it, is a bug, and I am suspicious about whether that expression is actually evaluated correctly.

Interestingly, this [test form](https://docs.google.com/spreadsheets/d/14YUkeEVSCJlDGG0plqnVqcS0z9CY1HcmgfT2Sk9LJvY/edit#gid=0) does not seem to pass ODK Validate and (current) Enketo validation.
(see [or or.xml.txt](https://github.com/enketo/enketo-express/files/5771596/or.or.xml.txt) and test in https://validate.enketo.org)

What kind of logic type (constraint, relevant, calculation etc) was the double "or or" used in? If we find it bypasses an ODK/Enketo validate check, we should file an issue.

**Comment by NoelCartONG** [comment]
It's a relevancy, please see below test example.

It converts to xml format without error using https://getodk.org/xlsform/ and the resulting xml file produces no error when tested using the link you sent above.  The error can be seen in the xml file too and as you predict it does cause problems in functionality.  The first part of the or statement works but the second part fails.  In the form where the error was originally spotted the if statement had 19 clauses and I can check with my colleague who is in the process of building the form but I think this means that the last of those 19 clauses was failing and the others were working as normal.  Our system is normally Kobo toolbox and ODK validate based checking.

[or or.xlsx](https://github.com/enketo/enketo-express/files/5774730/or.or.xlsx)

**Comment by lognaturel** [comment]
This is where we had previously seen `or or`, @MartijnR. I think this particular issue can be closed, does that sound right?

**Comment by MartijnR** [comment]
Ah, there it is! Yes, I think so.
