### ISSUE TITLE
new Evaluator issues with and/or inside function call

### ISSUE THREAD

**Issue by MartijnR** [enketo/enketo-express#227]
* [x] Martijn to check http://localhost:8005/XfnxYcR0KWApbMfaK96UMoYYNU2XX0i (form 10103 on Centro) after a fix has been implemented.

_Originally posted by @MartijnR in https://github.com/enketo/enketo-express/issues/224#issuecomment-754234814_

enketo/openrosa-xpath-evaluator#67 
enketo/openrosa-xpath-evaluator#71

**Comment by MartijnR** [comment]
enketo-core: http://localhost:8005/?xform=10103.xml

**Comment by joshuaberetta** [comment]
@MartijnR, it looks like we're seeing this come up here: https://community.kobotoolbox.org/t/please-help-test-enketo-2-7-3/20018/28
