### ISSUE TITLE
How to change the default page title?

### ISSUE THREAD

**Issue by amks1** [enketo/enketo-express#235]
I'm referring to the "Enketo for Kobotoolbox" which is the default title for any form, login page, etc. 
Changing the "app name" in the config.json file only changes the app name in the home page, and not the titles. So what's the way to change the page title?

Thanks.

**Comment by MartijnR** [comment]
The title is changed dynamically to the form name, see e.g. https://enke.to/widgets.

However, maybe you're referring to this existing issue? https://github.com/enketo/enketo-express/issues/215

I'm assuming you are, but if not, please reopen this issue.

**Comment by amks1** [comment]
Actually my issue is not with the dynamically generated form titles, but

- the title that shows up just before the form title is pulled (for a second or two)
- the title on the login page.

Where can we change the default value of those?

**Comment by MartijnR** [comment]
That's what that issue is referring to. 

For the first few seconds, it should be the app name in config.json that you already found. Did you restart the application after changing the value?

Note, that the value "Enketo for Kobotoolbox" does not occur in our codebase, so I'm not sure how you could be seeing that. Maybe you're running a very old version?

**Comment by amks1** [comment]
Yes, I tried restarting. I too searched for the Kobotoolbox literal in all the files but couldn't find any. 
That's why I am puzzled as to where the value is coming from.

**Comment by MartijnR** [comment]
It's definitely "app name" for the login page, like https://enke.to/login, so for some reason that config.json file you're editing is not the one that's used by the app. You could confirm by changing other things like the default theme.

Are you using docker?

**Comment by amks1** [comment]
I tried changing the disable draft option, and it works (no option to save draft). So the config file is working.

Yes, using docker.

**Comment by MartijnR** [comment]
I don't use docker myself, but let's try to get help from a real developer. @jnm, I'm guessing you know exactly what's going on here and can help. Please?
