### ISSUE TITLE
installation fails with npm 7

### ISSUE THREAD

**Issue by MartijnR** [enketo/enketo-express#240]
Probably out of our control. Issue is with https://github.com/albanm/node-libxslt.

* [x] temporarily restrict npm versions in `engine` in package.json
* [ ] look into libxslt issue with npm 7

**Comment by MartijnR** [comment]
npm v7 does work for enke.to but that's probably because libxslt was already built (with npm 6) before upgrading npm

**Comment by lognaturel** [comment]
Should now be fixed.
