### ISSUE TITLE
When an encrypted form has a space in its formID, submission to data server fails with 404

### ISSUE THREAD

**Issue by lognaturel** [enketo/enketo-express#252]
v2.7.3

**Describe the bug**
When an encrypted form has a space in its formID, submission to data server fails with 404. See [Central issue](https://github.com/getodk/central-backend/issues/364) and original [ODK forum report](https://forum.getodk.org/t/odk-central-change-to-encrypted-form-once-already-started-data-collection-breaks-submissions/33082) from LSHTM. We suspect this would affect any formID that needs to be URL-encoded.

**To Reproduce**
1. Create a form definition with a space in its formID and an encryption key on a data server
2. Successfully create a link for and open the form in Enketo
3. Fill out the form and try to submit it
4. See `Submission service on data server not found. (404)`

**Expected behavior**
Forms with any formID can be encrypted.

Suspicious:
https://github.com/enketo/enketo-express/blob/3f353ea44934045e185db71e26ec331146ec2610/public/js/src/module/controller-webform.js#L268

My next step would be to try this locally to see what is actually being sent to the data server. I can't find a way to do that on a production server.

**Comment by MartijnR** [comment]
Thanks. Possible link with https://github.com/enketo/enketo-express/issues/35 (but probably not).

**Comment by lognaturel** [comment]
To be clear, this /only/ affects encrypted forms. FormIDs with spaces work fine generally. That's why that line which relates only to encrypted forms seems like a very likely culprit.

**Comment by lognaturel** [comment]
Seems that I can change 
https://github.com/enketo/enketo-express/blob/3f353ea44934045e185db71e26ec331146ec2610/public/js/src/module/controller-webform.js#L268 
to `id: form.id` with no change in behavior.

The issue seems to be with the formID written in the submission.

**Comment by lognaturel** [comment]
I currently suspect this has to do with the parsing that happens to build a `Form`.  
* I've confirmed that `form.id` always has underscores instead of spaces. But it looks like that's not used in building a non-encrypted submission so it doesn't cause problems in that case.
* In `controller-webform` after `form = new Form( formEl, data, formOptions );` I can confirm that `data` has the raw XML with spaces for the `formId`. And I can confirm that `form.id` has the underscores.

What I don't yet understand is why the `record` logging I described above is different. Maybe it has to do with the way the `encrypted` attribute is added to the submission xml.

**Comment by lognaturel** [comment]
- [ ] Replace https://github.com/enketo/enketo-express/blob/3f353ea44934045e185db71e26ec331146ec2610/public/js/src/module/controller-webform.js#L268 with call on form.id
- [ ] Update `enketo-core` once there's a release with `enketo-transformer` v1.43
