### ISSUE TITLE
Facilitate HTTP caching of static resources

### ISSUE THREAD

**Issue by MartijnR** [enketo/enketo-express#259]
This issue is not about actually implementing a HTTP cache (which may follow in a different issue). However,  EE installers may use e.g. NGINX to implement HTTP caching themselves for JS bundles and CSS files. This issue is about making the Service Worker cache (used to cache the application for offline use) robust enough to not break when a HTTP cache is used.

**Comment by MartijnR** [comment]
The question is whether the Service Worker (offline app cache) can be thrown off by any type of app/NGINX HTTP caching.

https://web.dev/service-worker-caching-and-http-caching/

Every time Enketo Express is updated (determined in config-model.js with git describe --tags), the Service Worker cache is thrown away and rebuilt (when online).

when new version is downloaded (git pull) the version won't update immediately as it is only read once during app start/restart
new JS and CSS is rebuilt
app is restarted, prompting version change, and cache refresh
If at point 3, the browser is serving a pre-update version of a Service-Worker-cached resource, there will be a problem with incorrect resources - possibly mismatched, that would not self-resolve because the Service-Worker cache does not expire.

https://jakearchibald.com/2016/caching-best-practices/

I think the simplest solution is to change the service worker to:

* [ ] use new Request( CSSORJS_URL, { cache: 'reload' } in cache.addAll( resources )
see https://developer.mozilla.org/en-US/docs/Web/API/Request/cache

However, this would only take care of the few explicit resources.

* [ ] use same {cache: 'reload'} option for non-explicit resources cached by the Service Worker
The above would work for both NGINX-set cache headers for static resources as well as for app-set cache headers.

**Comment by lognaturel** [comment]
https://github.com/OpenClinica/enketo-express-oc/issues/482 has context on motivation and verification done. I'm still digesting and thinking through implications.

**Comment by lognaturel** [comment]
Closed by https://github.com/enketo/enketo-express/pull/261?
