### ISSUE TITLE
Query parameters are decoded twice

### ISSUE THREAD

**Issue by joshuaberetta** [enketo/enketo-express#272]
**Describe the bug**

xref: https://community.kobotoolbox.org/t/bug-found-in-enketo-forms-when-handling-prefilled-field-containing-a-percent-character/19821

**To Reproduce**

1. Create a form with a single `text` question with name `name`
2. Launch Enketo URL and include `d` query parameter to pre-fill question that contains a `%` symbol (URL encoded) (`?d[name]=10%25%20tax`)
3. Infinite spinner
4. Try double encoding the `%`: `%2525`
5. Success

We use `decodeURIComponent` here:
https://github.com/enketo/enketo-express/blob/8392f01a823c0d78ecf77be3b49af9291216cc8a/public/js/src/module/settings.js#L38
But it's already been called in `_getAllQueryParams()` here:
https://github.com/enketo/enketo-express/blob/8392f01a823c0d78ecf77be3b49af9291216cc8a/public/js/src/module/settings.js#L107

So we get:
```javascript
decodeURIComponent(decodeURIComponent('10%25%20tax'))
```
```
Uncaught URIError: malformed URI sequence
    <anonymous> debugger eval code:1
```

**Comment by MartijnR** [comment]
Oops!

* [ ] also check if the API encodes twice (since these URLs  are supposed to be crafted by the API.

**Comment by joshuaberetta** [comment]
@MartijnR, how would you go about testing this change in `public/js/src/module/settings.js`? I'm battling to find the correct way to do it. 

```diff
diff --git a/public/js/src/module/settings.js b/public/js/src/module/settings.js
index cc31bbd..adaaaa6 100644
--- a/public/js/src/module/settings.js
+++ b/public/js/src/module/settings.js
@@ -35,7 +35,7 @@ for ( const p in queryParams ) {
         // URLs with encoded brackets as well us not-encode brackets will work.
         const matches = decodeURIComponent( p ).match( /d\[(.*)\]/ );
         if ( matches && matches[ 1 ] ) {
-            settings.defaults[ matches[ 1 ] ] = decodeURIComponent( queryParams[ p ] );
+            settings.defaults[ matches[ 1 ] ] = queryParams[ p ];
         }
     }
 }
```

**Comment by MartijnR** [comment]
I personally would not add a test for this (because I also wouldn't know what would make sense), except a test for the API response if that response also includes a double-encoded parameter.
