### ISSUE TITLE
Error displayed when submitting an edit

### ISSUE THREAD

**Issue by eyelidlessness** [enketo/enketo-express#296]
**Describe the bug**
An error is shown when submitting an edit to a submission. **Note:** this error occurs after the edit is submitted successfully.

**To Reproduce**
Steps to reproduce the behavior. If applicable please include the smallest possible XLSForm or XForm (as zip or link).
1. Submit a record
2. Open the record to edit
3. Click submit

**Expected behavior**
No error is shown.

**Screenshots**
![image](https://user-images.githubusercontent.com/199830/128760919-ce55a7fb-c10c-457b-ba55-7c458de73a73.png)

**Browser and OS (please complete the following information):**
 - OS: macOS
 - Browser: Chrome

**Additional context**
 1. This occurs because the data store is accessed to update last-saved instances for cases where the form is reset, but that should not be done in edit mode, where submission redirects.
 2. This regression is present in the current release, but also present in #293, so there will be corresponding changes for both.

**Comment by lognaturel** [comment]
Does/did this also affect single and single/once views? Any others?

**Comment by eyelidlessness** [comment]
Yes. It affects any view that redirects after submission. I didn’t test those manually, but I’m fairly certain the fixes in #297 and #293 address those cases too, because the code path to update the form is now implemented directly in `_resetForm`, which is only called if `redirect` is false.
