### ISSUE TITLE
Offline capability for "query parameter" authentication

### ISSUE THREAD

**Issue by vituslehner** [enketo/enketo-express#308]
Hi dear Enketo team,

in the Enketo configuration docs it says under the heading "query parameter to pass to submission": 

> Specifies the name of a query parameter that will be copied from an Enketo URL to the submission and formList requests. [...] **Does not apply to offline-capable webforms.**

Source: https://enketo.github.io/enketo-express/tutorial-10-configure.html#query-parameter-to-pass-to-submission

Why does this not apply for Offline forms? I can actually make this work with ODK Central's public links which - to my understanding - use this query parameter. To enable the Enketo Offline-mode, I change the `/single/` part of the URL to `/x/`. No errors occur and I can successfully submit (first to queue, then to server).

What is the reason that this is not officially considered as working, and what would be needed to have it working officially?

Thanks!

**Comment by MartijnR** [comment]
Hi @vituslehner,

This dates back to the old days when Enketo was using ApplicationCache and a hack that abused the URL fragment identifier (\#). Now that we've switched to ServiceWorkers, this restriction no longer applies, and it appears according to your findings that this magically started working. 

Closing to continue here: https://github.com/enketo/enketo-express/issues/228

**Comment by lognaturel** [comment]
A PR to update the docs would be appreciated, @vituslehner!

**Comment by eyelidlessness** [comment]
We should also prioritize documentation of security/privacy risks around putting secrets in query parameters. And probably provide guidance around mitigation if this is part of the documented API.

By default query parameters are logged by every web server, and visible to every primary network/proxy/CDN/VPN. We should make sure those risks are widely known if this is a use case we’re supporting.

**Comment by vituslehner** [comment]
Hi @lognaturel and @eyelidlessness,

I'm happy to contribute to the docs, was just wondering how quickly a "*works by accident*" should be put into the docs, or whether some more testing should be done before.

If you feel like this is indeed resolved, I will prepare a PR.

**Comment by lognaturel** [comment]
We've had ODK users make extensive use of offline public links so it's definitely a combination of features that support should be maintained for and that we know works. It's probably not how Central will eventually surface offline links if it ever does but the intent is to maintain that functionality. Thanks for following up, @vituslehner!

@eyelidlessness I think risks are more something that clients of Enketo (e.g. Central) should address in the context of their particular usage. For example, Central docs could say a little bit more about the mechanics of public links and their implications.
