### ISSUE TITLE
Docker: Use base image with Node 16?

### ISSUE THREAD

**Issue by jnm** [enketo/enketo-express#331]
Now that #298 has been merged and Node 16 is used for CI, should we change the [Dockerfile](https://github.com/enketo/enketo-express/blob/e2b4b92870d4cdc2d625a02f3a3445da8652aa3e/Dockerfile#L1) to match? I can submit a PR if desired. Thanks.

**Comment by yanokwa** [comment]
I don't feel strongly about it, but seems like a reasonable thing to do. @eyelidlessness?

**Comment by jnm** [comment]
Maybe if it's not a big deal, we can just wait. The Node 16 base image includes npm 8.1.0, and I had trouble installing libxslt with npm 7+. It does install successfully with npm 6.14.15. We'd have to downgrade npm in our own Dockerfile, which isn't a big deal, but maybe it's not worth the effort to upgrade if Node 14 is fine for now in production.

**Comment by jnm** [comment]
With CI now testing [both Node 14 and 16](https://github.com/enketo/enketo-express/blob/d350a63171b16bf8f3bf2f3b11a05be9430c1b66/.github/workflows/ci.yml#L16-L18), I don't think there's any need to keep this issue open.
