### ISSUE TITLE
Error: Attachment not found for kobo instance media

### ISSUE THREAD

**Issue by amks1** [enketo/enketo-express#355]
**Describe the bug**
When installed with Kobotoolbox 2.021.41, media is not visible in the `edit` and `view` pages for instances.

**To Reproduce**
1. Install Kobotoolbox 2.021.41 with Enketo Express v3.0.3
2. Add a form with an image question
3. Open the form, upload  a photo and submit
4. Go to table view in kobotoolbox, click on the submission's view icon then click on the View button.
5. The image will not load. Console shows 404.

**Expected behavior**
Images should be visible.

**Screenshots**
![image](https://user-images.githubusercontent.com/68153785/139558480-c9f3ff54-220e-49d9-9695-6ff79e7b08c4.png)

**Browser and OS (please complete the following information):**
 - Chrome

**Additional context**
Enketo Express built from commit `dde2313`

**Comment by lognaturel** [comment]
Could possibly be https://github.com/enketo/enketo-express/issues/351

It would be helpful to see the media request url for a working version of Enketo to see what Kobo expects.

**Comment by amks1** [comment]
It's working on 2.8.1 on Kobotoolbox servers, but I myself was not able to test it due to [this](https://github.com/enketo/enketo-express/pull/317#issuecomment-929745484) error. Maybe @jnm can help?

**Comment by jnm** [comment]
Hi @amks1, is there a reason you need 3.0.3 with KoBoToolbox right now? We're not really ready to start testing that release combination yet.

KoBo production servers use https://hub.docker.com/r/kobotoolbox/enketo-express-extra-widgets/tags, built from https://github.com/kobotoolbox/enketo-express-extra-widgets/blob/master/Dockerfile, whose `Dockerfile` contains a `npm install` step that avoids the `eslint` error you linked to. You could use that `Dockerfile` in your local environment if you'd like.
