### ISSUE TITLE
EDIT Instance

### ISSUE THREAD

**Issue by enketo-issue-mover** [enketo/enketo-express#38]
_From @iahmedani on June 16, 2016 3:52_

Dear Martin,

Hope you are doing well.

I am trying to edit instance but the system gives me an error " Record not present. It may have expired.

Url is http://abc.xyz/edit/::YYYy?instance_id=?d4b2b8fa-1740-4e48-8540-7c15781e7886&return_url=http://abc.xyz/edit
![image](https://cloud.githubusercontent.com/assets/17918895/16105005/b52899aa-339f-11e6-8dc6-8847eeb68010.png)

_Copied from original issue: kobotoolbox/enketo-express#520_

**Comment by enketo-issue-mover** [comment]
_From @MartijnR on June 16, 2016 21:44_

The URL expires very quickly. It is meant to be used programmatically with an immediate redirect to the returned URL. Does your issue occur with KoBoCat, Ona, Formhub?

**Comment by enketo-issue-mover** [comment]
_From @iahmedani on June 17, 2016 0:14_

I am using on ODKAggregate server. But it do not spends one second, directly shows this error

**Comment by enketo-issue-mover** [comment]
_From @MartijnR on June 20, 2016 15:19_

Can you provide an actual curl API call (only change the api key, nothing else)?

**Comment by enketo-issue-mover** [comment]
_From @iahmedani on June 21, 2016 4:2_

``` bash
curl --user xyz: -d "server_url=http://me.wfp.org.pk:8050/ODKAggregate&form_id=PDM_CMAM_1&instance=<data><node>DM_CMAM_UCDaag Besud _Location_Daag Besud</node></data>&instance_id=d3effa60-eae1-40da-8c2b-b1dd56670be1&return_url=http://me.wfp.org.pk" http://10.11.70.36/api/v2/instance
```

**Comment by enketo-issue-mover** [comment]
_From @MartijnR on June 21, 2016 15:54_

Will investigate if there is a bug if the instance XML does not match the XForm instance. I'm assuming the primary instance does not have a root node with name `data`. You should in that case get a different error message if you redirect immediately.

It may help if you could also share the XForm or XLSForm.

**Comment by luisbauti92** [comment]
@MartijnR 
Yes, I'm using ODK Aggregate, it's possible to edit a record? any idea  how to see the xml of a record?


`<h:html xmlns="http://www.w3.org/2002/xforms" xmlns:h="http://www.w3.org/1999/xhtml" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:jr="http://openrosa.org/javarosa">
  <h:head>
    <h:title>Levantamiento</h:title>
    <model>
      <instance>
        <data id="build_Untitled-Form_1554821025">
          <meta>
            <instanceID/>
          </meta>
          <nombre/>
          <telefono/>
          <fecha/>
          <ubicacion/>
          <foto/>
          <tipo_cliente/>
          <estabilidad_domiciliaria/>
          <nivel_de_vida>
            <estabilidad_negocio/>
            <destino/>
          </nivel_de_vida>
        </data>
      </instance>
      <itext>
        <translation lang="English">
          <text id="/data/nombre:label">
            <value>Nombre</value>
          </text>
          <text id="/data/nombre:hint">
            <value>Nombre</value>
          </text>
          <text id="/data/telefono:label">
            <value>Teléfono</value>
          </text>
          <text id="/data/telefono:hint">
            <value>Teléfono</value>
          </text>
          <text id="/data/fecha:label">
            <value>Fecha</value>
          </text>
          <text id="/data/fecha:hint">
            <value>Fecha</value>
          </text>
          <text id="/data/ubicacion:label">
            <value>Ubicación</value>
          </text>
          <text id="/data/ubicacion:hint">
            <value>Ubicación</value>
          </text>
          <text id="/data/foto:label">
            <value>Foto</value>
          </text>
          <text id="/data/foto:hint">
            <value>Foto</value>
          </text>
          <text id="/data/tipo_cliente:label">
            <value>Tipo Cliente</value>
          </text>
          <text id="/data/tipo_cliente:hint">
            <value>Tipo Cliente</value>
          </text>
          <text id="/data/tipo_cliente:option0">
            <value>Deudor</value>
          </text>
          <text id="/data/tipo_cliente:option1">
            <value>Co Deudor</value>
          </text>
          <text id="/data/tipo_cliente:option2">
            <value>Garante</value>
          </text>
          <text id="/data/estabilidad_domiciliaria:label">
            <value>Estabilidad Domiciliaria</value>
          </text>
          <text id="/data/estabilidad_domiciliaria:hint">
            <value>Estabilidad Domiciliaria</value>
          </text>
          <text id="/data/estabilidad_domiciliaria:option0">
            <value>Vivienda Propia</value>
          </text>
          <text id="/data/estabilidad_domiciliaria:option1">
            <value>Vivienda Familiar</value>
          </text>
          <text id="/data/estabilidad_domiciliaria:option2">
            <value>Alquilada</value>
          </text>
          <text id="/data/estabilidad_domiciliaria:option3">
            <value>Anticrético</value>
          </text>
          <text id="/data/estabilidad_domiciliaria:option4">
            <value>Otro</value>
          </text>
          <text id="/data/nivel_de_vida:label">
            <value>Nivel de Vida</value>
          </text>
          <text id="/data/nivel_de_vida/estabilidad_negocio:label">
            <value>Estabilidad de Negocio</value>
          </text>
          <text id="/data/nivel_de_vida/estabilidad_negocio:hint">
            <value>Estabilidad de Negocio</value>
          </text>
          <text id="/data/nivel_de_vida/estabilidad_negocio:option0">
            <value>Vivienda Propia</value>
          </text>
          <text id="/data/nivel_de_vida/estabilidad_negocio:option1">
            <value>Vivienda Familiar</value>
          </text>
          <text id="/data/nivel_de_vida/estabilidad_negocio:option2">
            <value>Alquilada</value>
          </text>
          <text id="/data/nivel_de_vida/estabilidad_negocio:option3">
            <value>Anticrético</value>
          </text>
          <text id="/data/nivel_de_vida/estabilidad_negocio:option4">
            <value>Otro</value>
          </text>
          <text id="/data/nivel_de_vida/destino:label">
            <value>Destino</value>
          </text>
          <text id="/data/nivel_de_vida/destino:hint">
            <value>Destino</value>
          </text>
          <text id="/data/nivel_de_vida/destino:option0">
            <value>Ahorros</value>
          </text>
          <text id="/data/nivel_de_vida/destino:option1">
            <value>Inversiones y Mejoras</value>
          </text>
          <text id="/data/nivel_de_vida/destino:option2">
            <value>Pago deudas</value>
          </text>
          <text id="/data/nivel_de_vida/destino:option3">
            <value>Familia</value>
          </text>
          <text id="/data/nivel_de_vida/destino:option4">
            <value>Otros</value>
          </text>
        </translation>
      </itext>
      <bind nodeset="/data/meta/instanceID" type="string" readonly="true()" calculate="concat('uuid:', uuid())"/>
      <bind nodeset="/data/nombre" type="string" required="true()"/>
      <bind nodeset="/data/telefono" type="int"/>
      <bind nodeset="/data/fecha" type="date"/>
      <bind nodeset="/data/ubicacion" type="geopoint"/>
      <bind nodeset="/data/foto" type="binary"/>
      <bind nodeset="/data/tipo_cliente" type="select1"/>
      <bind nodeset="/data/estabilidad_domiciliaria" type="select"/>
      <bind nodeset="/data/nivel_de_vida/estabilidad_negocio" type="select"/>
      <bind nodeset="/data/nivel_de_vida/destino" type="select"/>
    </model>
  </h:head>
  <h:body>
    <input ref="/data/nombre">
      <label ref="jr:itext('/data/nombre:label')"/>
      <hint ref="jr:itext('/data/nombre:hint')"/>
    </input>
    <input ref="/data/telefono">
      <label ref="jr:itext('/data/telefono:label')"/>
      <hint ref="jr:itext('/data/telefono:hint')"/>
    </input>
    <input ref="/data/fecha">
      <label ref="jr:itext('/data/fecha:label')"/>
      <hint ref="jr:itext('/data/fecha:hint')"/>
    </input>
    <input ref="/data/ubicacion">
      <label ref="jr:itext('/data/ubicacion:label')"/>
      <hint ref="jr:itext('/data/ubicacion:hint')"/>
    </input>
    <upload ref="/data/foto" mediatype="image/*">
      <label ref="jr:itext('/data/foto:label')"/>
      <hint ref="jr:itext('/data/foto:hint')"/>
    </upload>
    <select1 ref="/data/tipo_cliente">
      <label ref="jr:itext('/data/tipo_cliente:label')"/>
      <hint ref="jr:itext('/data/tipo_cliente:hint')"/>
      <item>
        <label ref="jr:itext('/data/tipo_cliente:option0')"/>
        <value>1</value>
      </item>
      <item>
        <label ref="jr:itext('/data/tipo_cliente:option1')"/>
        <value>2</value>
      </item>
      <item>
        <label ref="jr:itext('/data/tipo_cliente:option2')"/>
        <value>3</value>
      </item>
    </select1>
    <select ref="/data/estabilidad_domiciliaria">
      <label ref="jr:itext('/data/estabilidad_domiciliaria:label')"/>
      <hint ref="jr:itext('/data/estabilidad_domiciliaria:hint')"/>
      <item>
        <label ref="jr:itext('/data/estabilidad_domiciliaria:option0')"/>
        <value>1</value>
      </item>
      <item>
        <label ref="jr:itext('/data/estabilidad_domiciliaria:option1')"/>
        <value>2</value>
      </item>
      <item>
        <label ref="jr:itext('/data/estabilidad_domiciliaria:option2')"/>
        <value>3</value>
      </item>
      <item>
        <label ref="jr:itext('/data/estabilidad_domiciliaria:option3')"/>
        <value>4</value>
      </item>
      <item>
        <label ref="jr:itext('/data/estabilidad_domiciliaria:option4')"/>
        <value>5</value>
      </item>
    </select>
    <group ref="/data/nivel_de_vida">
      <label ref="jr:itext('/data/nivel_de_vida:label')"/>
      <select ref="/data/nivel_de_vida/estabilidad_negocio">
        <label ref="jr:itext('/data/nivel_de_vida/estabilidad_negocio:label')"/>
        <hint ref="jr:itext('/data/nivel_de_vida/estabilidad_negocio:hint')"/>
        <item>
          <label ref="jr:itext('/data/nivel_de_vida/estabilidad_negocio:option0')"/>
          <value>1</value>
        </item>
        <item>
          <label ref="jr:itext('/data/nivel_de_vida/estabilidad_negocio:option1')"/>
          <value>2</value>
        </item>
        <item>
          <label ref="jr:itext('/data/nivel_de_vida/estabilidad_negocio:option2')"/>
          <value>3</value>
        </item>
        <item>
          <label ref="jr:itext('/data/nivel_de_vida/estabilidad_negocio:option3')"/>
          <value>4</value>
        </item>
        <item>
          <label ref="jr:itext('/data/nivel_de_vida/estabilidad_negocio:option4')"/>
          <value>5</value>
        </item>
      </select>
      <select ref="/data/nivel_de_vida/destino">
        <label ref="jr:itext('/data/nivel_de_vida/destino:label')"/>
        <hint ref="jr:itext('/data/nivel_de_vida/destino:hint')"/>
        <item>
          <label ref="jr:itext('/data/nivel_de_vida/destino:option0')"/>
          <value>1</value>
        </item>
        <item>
          <label ref="jr:itext('/data/nivel_de_vida/destino:option1')"/>
          <value>2</value>
        </item>
        <item>
          <label ref="jr:itext('/data/nivel_de_vida/destino:option2')"/>
          <value>3</value>
        </item>
        <item>
          <label ref="jr:itext('/data/nivel_de_vida/destino:option3')"/>
          <value>4</value>
        </item>
        <item>
          <label ref="jr:itext('/data/nivel_de_vida/destino:option4')"/>
          <value>5</value>
        </item>
      </select>
    </group>
  </h:body>
</h:html>`

My XML Form

**Comment by MartijnR** [comment]
> Yes, I'm using ODK Aggregate, it's possible to edit a record? 

No, it is not, unless you modify ODK Aggregate's code. ODK has no plans to add this functionality to ODK Aggregate. However, ODK does [have plans to add this functionality to ODK Central](https://forum.opendatakit.org/t/integration-of-enketo-into-odk-central/13992/37)(which will replace ODK Aggregate).

> any idea how to see the xml of a record?
No, I don't.

A pragmatic immediate solution would be to move your data to a KoBoToolbox or Ona account (using ODK Briefcase). Both of these have built-in support to edit submitted data using Enketo.
