### ISSUE TITLE
Big problem with coverage

### ISSUE THREAD

**Issue by thednp** [enketo/enketo-express#411]
**Describe the bug**
I'm here to thank you very much for your [esbuild-plugin-istanbul](https://github.com/enketo/enketo-express/blob/master/tools/esbuild-plugin-istanbul.js), it really helped. I only wish you would publish this to npm and make it work with `@istanbuljs/load-nyc-config`, but I somehow managed that too :)

**To Reproduce**
Take a 5 minutes break from your computer and have some fun.

**Expected behavior**
LOL for 5 minutes.

**Screenshots**
![image](https://user-images.githubusercontent.com/6761246/164412583-251e11bb-dfda-493d-bcd1-d9daf3822dd7.png)

**Browser and OS (please complete the following information):**

**Additional context**
I hope you like April pranks :)

**Comment by lognaturel** [comment]
Haha, thanks for that feedback, I'm sure @eyelidlessness will be thrilled after taking the time to follow the reproduction steps. 😅

Happy coverage reporting.

**Comment by thednp** [comment]
Hi.

Sorry to bother you guys, but after some testing, working flawless on my machine, it fails on [Github actions](https://github.com/thednp/dommatrix/runs/6141094673?check_suite_focus=true) with the following error:

```
 Cannot find coverage file /home/runner/work/dommatrix/dommatrix/.nyc_output/out.json
Skipping coverage report
```

Any suggestion is greatly appreciated.

**Comment by thednp** [comment]
Found that too: my RegExp was wrong, I had to change: `/\\dommatrix\\src\\/` to `/./`, and added a path check
 similar to yours, [the result is glorious](https://github.com/thednp/dommatrix/runs/6188472928?check_suite_focus=true)

Cheers guys
