### ISSUE TITLE
Image missing in file upload [more information needed]

### ISSUE THREAD

**Issue by eyelidlessness** [enketo/enketo-express#436]
> @lognaturel , we seem to be on 3.1.0 but we're experiencing the same issue. We're unable to see the images as shown. What we wanted to do is print and have the image shown in the printout but it doesn't seem to show at all.
![Screenshot 2022-05-31 at 15 02 35](https://user-images.githubusercontent.com/77043654/171168695-afe8362f-aa7a-481e-8d48-60c40a06f576.png)

_Originally posted by @eochieng-lab in https://github.com/enketo/enketo-express/issues/394#issuecomment-1142032606_

- - -

Opening as a new issue as it appears to be a different scenario. @eochieng-lab, could you provide more detail about this? These would help:

- The form definition and images used, if possible
- Steps you took before seeing this (e.g. were you editing a submission, and this was posted in #394 because it mentioned editing?)

**Comment by lognaturel** [comment]
This looks like a submission edit. I edited a submission made to Central with an image that has spaces in the URL. I verified the image is visible inline and in the print view. This might be Ona-specific.

**Comment by eochieng-lab** [comment]
@lognaturel , yes it is a submission edit and you are right. I've tried it on Kobo Toolbox and it seems I can't replicate there so it may be specific to our instance. Thanks for this clarification at @lognaturel. I think for now we can also close this while I liaise with the engineers on our side to see whether this can be fixed.
