### ISSUE TITLE
Likely memory leak under high load in 3.1.0+

### ISSUE THREAD

**Issue by noliveleger** [enketo/enketo-express#443]
**Describe the bug**
When using the docker image of Enketo Express, we can notice the RAM usage is increasing constantly (with load).
From a fresh start, RAM usage is about 600-800 MB but after few days it becomes several GB.
_Notes: It depends on number of requests received_

**To Reproduce**
Use a load tester such as `siege` or `locust` and hit the root url. http://enketo-express/. 
Set it to hit enketo with 3-4 requests/s. After 24 hours, the RAM used by EE docker container should be around 8 GB, after 3 days ~24 GB.

**Expected behavior**
The RAM usage should stay below a reasonable amount (e.g 2GB max).
 
**Screenshots**
None, but I can re-run my tests to get ones if needed

**Browser and OS (please complete the following information):**

-  Docker version 20.10.14, build a224086
-  Ubuntu 20.04 LTS

**Additional context**
Enketo-Express docker container is behind NGINX which serves as the reverse proxy.

**Comment by lognaturel** [comment]
Thanks for the detailed report, @noliveleger. ODK Central v1.5 has been running Enketo Express v4.1.0 for about 20 days. I just looked at monitoring and don't see any evidence of this behavior. But any given Central server doesn't get the kind of load you're describing very often (single-tenant).

Do you believe this is new behavior? If you've been tracking these metrics before, what's the last version you didn't see this behavior with? Have you changed anything about your configuration (e.g. capping max processes https://github.com/enketo/enketo-express/pull/415)?

**Comment by noliveleger** [comment]
Hello @lognaturel, 
Actually, I've seen this with `3.1.0` so I decided to test with the latest release available just to be sure it was not related to this particular version. So I guess it is not a new behaviour. 
I've discover this issue during a load test to find bottlenecks in our setup when we are facing such a load. In my tests, I used Enketo root because it was easier to setup (i.e. no auth) and see how nodejs would behave, but in real case, I would only use the root for health check monitoring (so even if we can have 3-4 requests/s on API endpoints, root should receive such traffic). I can retry my tests with another `GET` API endpoint instead to validate it's not only happening from  `/`.

**Comment by lognaturel** [comment]
> I've seen this with 3.1.0

Interesting! Maybe you could try with the oldest image at https://github.com/enketo/enketo-express/pkgs/container/enketo-express? My guess is that it’s a long-standing issue. 

> retry my tests with another GET API endpoint instead to validate it's not only happening from /.

I’m having a hard time imagining how it could be / only but i guess stranger things have happened! 

Have you seen this on a production instance or only under artificially sustained load?

**Comment by lognaturel** [comment]
> Is 2.8.1 is the oldest (from the link you provided). I found 2.2.0 on docker hub?

Yes, that sounds right. Trying v2.8.1 would be insightful because it's when @eyelidlessness and I started being more involved. If it predates that, it's going to be even harder to hunt down.

**Comment by noliveleger** [comment]
Hello @lognaturel,

I finally tested 2.2.0, 2.8.1, 3.0.4, 3.0.5 and again 3.1.0 (just to be sure). 
The tests were exactly the same. I've used `locust` to hit `/` with about 3 requests/s for about 3 hours. 

For all the versions except 3.1.0, memory usage stayed around 800 MB. Using 3.1.0, it increased up to 2 GB. 
So it seems to have been introduced in 3.1.0.

**Comment by lognaturel** [comment]
Thanks so much for the sleuthing! I agree you've likely found the culprit. Will try to get a release out shortly.

**Comment by noliveleger** [comment]
You're right. Unfortunately, both packages don't seem to be maintained anymore.
