### ISSUE TITLE
node version in setup instructions is different to engines

### ISSUE THREAD

**Issue by alxndrsn** [enketo/enketo-express#446]
### Instructions

https://github.com/enketo/enketo-express/blob/master/tutorials/00-getting-started.md#manually:

> Install JS prerequisites: [Node.js](https://github.com/nodesource/distributions) (12.x LTS), [Grunt Client](http://gruntjs.com/).

### `package.json`

https://github.com/enketo/enketo-express/blob/master/package.json#L8:

        "node": ">=14 <17",

**Comment by alxndrsn** [comment]
It might be simpler to remove the specific node version from the documentation rather than trying to keep them permanently in sync.

**Comment by lognaturel** [comment]
Addressed in https://github.com/enketo/enketo
