### ISSUE TITLE
Upgrade from Redis 5 due to EOL status

### ISSUE THREAD

**Issue by yanokwa** [enketo/enketo-express#448]
Redis 5 was [EOL in Oct 2021](https://docs.redis.com/latest/rs/administering/product-lifecycle/#endoflife-schedule). We should upgrade to Redis 6 or Redis 7.

**Comment by jeverling** [comment]
I think the node-redis library might need upgrading.

Currently, version 3.1.2 will be installed. This version was released before Redis 7, which is the current major version of Redis.
There is a chance the node-redis library will just work fine with a newer version of Redis as was available when node-redis was pinned to the version that is currently used, but there could also be issues.

**Comment by lognaturel** [comment]
Ah yes, thank you! I've filed an issue about reviewing dependency versions at https://github.com/enketo/enketo/issues/9. We've now moved to a monorepo and will be archiving this one soon (https://github.com/enketo/enketo-express/issues/552)

**Comment by lognaturel** [comment]
And I can confirm that the current version works with Redis 7.2.

**Comment by jeverling** [comment]
That is good to know, thanks!
