### ISSUE TITLE
iOS: cannot assign to readonly property in NON-private browsing [?]

### ISSUE THREAD

**Issue by enketo-issue-mover** [enketo/enketo-express#45]
_From @MartijnR on May 13, 2016 17:8_

Can be reproduced in private browsing mode on latest iOS.

Probably cannot be fixed, but will check.

![screenshot](https://cloud.githubusercontent.com/assets/627350/15255758/3b38babc-18fb-11e6-9a73-ad3a61d9d132.png)

_Copied from original issue: kobotoolbox/enketo-express#504_

**Comment by enketo-issue-mover** [comment]
_From @MartijnR on May 13, 2016 17:12_

@dorey writes

My (possibly unhelpful) google-fu reveals

> At least on my configuration, I have narrowed it down to the i18n plugin. When I remove all i18n! imports it loads fine.

**Comment by enketo-issue-mover** [comment]
_From @MartijnR on May 13, 2016 17:38_

It seems odd that we have a handful of users using private browsing. I don't think this needs to be supported for offline-capable webforms (since the storage is supposed to not persist in private browsing).

However, if it also, under certain mysterious conditions, occurs in **regular browsing** in Safari on the latest iOS, then at least we may now be able to reliably reproduce it.

**Comment by enketo-issue-mover** [comment]
_From @MartijnR on May 13, 2016 19:53_

also try #434 as it's likely a db.js issue

**Comment by enketo-issue-mover** [comment]
_From @MartijnR on May 13, 2016 20:23_

can be reproduced on OS X safari as well in private browsing mode

**Comment by enketo-issue-mover** [comment]
_From @MartijnR on May 13, 2016 20:29_

occurs in call to db.open when assigning `.onsuccess` function: https://github.com/aaronpowell/db.js/blob/master/dist/db.js#L865 

The `request` variable is `null` in private browsing mode, so it's assigning a property to null.

**Comment by enketo-issue-mover** [comment]
_From @MartijnR on May 13, 2016 20:33_

Also occurs in FF in private mode with a more helpful 'store is not available' message.

Closing this. If it only occurs in private browsing mode, then it's not an issue. Better to output the error message the browser throws then to try rewriting this. The important thing is that an error is thrown upon loading, so there is no risk of people loosing data.

**Comment by enketo-issue-mover** [comment]
_From @MartijnR on May 13, 2016 21:17_

It has occurred in non-private browsing mode as well, but seemingly randomly. Not sure if same issue as cannot reproduce outside of private browsing.

Changed the issue to reflect non-private browing.

**Comment by MartijnR** [comment]
probably resolved
