### ISSUE TITLE
Form Previews & Edits show incorrect max file size

### ISSUE THREAD

**Issue by KipSigei** [enketo/enketo-express#452]
The `https://<server-url>/submission/max-size/<survey id>` endpoint seems to be failing with a 401 `Forbidden. Authorization Required` error.  The root cause for this is when enketo makes a `HEAD` request to the data server `enketo/<form-id>/submission` endpoint. Instead it shows the default `5mb` value.

![image](https://user-images.githubusercontent.com/19689992/179716673-25dfad04-8ee8-47a9-bfe7-12b27e06d2a9.png)

**Comment by lognaturel** [comment]
If this is still an issue for you can you please provide reproduction steps and context on what problem this is causing? There are also questions to answer at https://github.com/enketo/enketo-express/pull/457#issuecomment-1239813029

A reproduction with a server other than Ona would also help.

I've tried to quickly reproduce with Central. Given the following form which requires auth (token or cookie): https://test.getodk.cloud/-/single/c23b552637dec6a5d98f214d5c55f656286be9d27fc46577c847021f46fa757e?st=u!YbiJTN894xthYSwOGKR7aV92Ezy7Sr8ex4ahQgd5DXe7mjK5pf43pIOkubffDA

I can access https://test.getodk.cloud/-/submission/max-size/c23b552637dec6a5d98f214d5c55f656286be9d27fc46577c847021f46fa757e
