### ISSUE TITLE
Submission view-only mode throwing exception, error modal

### ISSUE THREAD

**Issue by joshuaberetta** [enketo/enketo-express#481]
**Describe the bug**

Opening a submission in the view-only model shows the following error model with message "can't access property "media", data.survey is undefined."

<img width="632" alt="enketo-error" src="https://user-images.githubusercontent.com/50016008/199536767-db81ef66-1f44-4ecc-9201-aa4697773c77.png">

**To Reproduce**

Open submission in view-only mode.

**Expected behavior**
Submission opens without error.

**Browser and OS (please complete the following information):**

-   OS: macOS
-   Browser: Firefox
-   Enketo Express: 4.1.2

**Additional context**
Kobo community thread: https://community.kobotoolbox.org/t/view-feature-gives-error/35012

**Comment by lognaturel** [comment]
Thanks for filing. Edit mode works, right?

**Comment by joshuaberetta** [comment]
@lognaturel, yes, fortunately editing works so it's not critical.

**Comment by JCsurfer** [comment]
Hi, still getting : "Cannot read properties of undefined (reading 'media')"

**Comment by lognaturel** [comment]
4.1.3 is out and should fix this. Please give it a try and let us know.

**Comment by JCsurfer** [comment]
Hi, it gives the same error

**Comment by lognaturel** [comment]
@JCsurfer are you sure you have updated the Enketo instance that your form server communicates with to 4.1.3?

**Comment by JCsurfer** [comment]
I am using the web version

**Comment by jnm** [comment]
@JCsurfer, KoboToolbox (which I administer) has not yet upgraded. Please note that the KoboToolbox support forum is the correct venue for your correspondence: https://community.kobotoolbox.org/t/view-feature-gives-error/35012/. If you'd like to participate here, you need to be able to run your own instance of Enketo Express and understand which version you are using. Thank you.
