### ISSUE TITLE
Syntax Error on Enketo

### ISSUE THREAD

**Issue by eochieng-lab** [enketo/enketo-express#489]
**Describe the bug**
It seems on some mobile devices, we seem to be getting the below `Syntax Error` when trying to open a webform:
![image](https://user-images.githubusercontent.com/77043654/202471820-eed9cca1-8dda-440a-b8d7-dabd2a861322.png)

From our testing (as Ona) as well as forums on Kobo, it seems the error occurs when the browser being used is not updated to the latest version. It seems this is only happening with later Enketo versions. Is there a fix that can be deployed on future Enketo releases that can clear this error and allow users to open the webforms on Enketo without this error being thrown?

**Comment by lognaturel** [comment]
Thanks for filing this! It should be fixed by https://github.com/enketo/enketo-core/pull/922

We'll release a new version of EE with that change in the next few days.

**Comment by eochieng-lab** [comment]
Thanks @lognaturel. Looking forward to it.

**Comment by lognaturel** [comment]
Released with Enketo Express 5.0.0. Please be sure to read the release notes and update the widgets configuration if necessary when upgrading.
