### ISSUE TITLE
Can this app be installed on m1/m2 macs?

### ISSUE THREAD

**Issue by MartijnR** [enketo/enketo-express#516]
Just wanted to enquire if this app installs without problems on M1/M2 macs. An issue was raised that it might not, and I don't have a modern Mac myself to test this.

**Comment by jnm** [comment]
According to @noliveleger:

> x86 emulation unfortunately (rosetta 2). I tried to make it run natively but it did not work. I did not dig further.

**Comment by lognaturel** [comment]
I haven't been able to get `libxmljs`/ `libxslt` to build without rosetta. We are hopeful that those can go away soon and I believe that is the only barrier (but not 100% sure).

**Comment by MartijnR** [comment]
Thanks!
