### ISSUE TITLE
When run in Docker as PID 1, slow termination time due to SIGTERM not being handled

### ISSUE THREAD

**Issue by bufke** [enketo/enketo-express#531]
**Describe the bug**

When the enketo express process is terminated, I would expect this to complete quickly. Perhaps in under 1 second. Instead, I see it taking 10-30 seconds to complete.

**To Reproduce**

1. Start ee docker container. For example the docker image kobotoolbox/enketo-express-extra-widgets:6.0.0
2. Stop the container

This can be reproduced with both `docker` and in Kubernetes, where the pod stays in a terminating state for a long time. In my tests, the server was not being utilized in any capacity. It is reproducible even with just 1 worker.

**Expected behavior**

The container immediate terminates. For comparison, the KoboToolbox KPI uwsgi based application takes 0.6s to exit. The official postgres:15 docker image takes 0.3s to exit.

**Screenshots**

**Browser and OS (please complete the following information):**

-  Tested in Ubuntu Linux and Amazon EKS using Docker

**Additional context**

The slower exit creates a less ideal developer experience. In a kubernetes environment, it slows the rolling deployment update strategy time. This leads to a longer period of time where the application might respond with either a newer or older version. It can also lead to adverse effects when a kubernetes cluster is rebalancing workloads.

**Comment by lognaturel** [comment]
Could it be that https://github.com/enketo/enketo-express/blob/master/Dockerfile#L18 should be updated so it doesn't get called as `/bin/sh -c` and thus immune to SIGTERM? Happy for a PR, here.

**Comment by bufke** [comment]
Thanks for the quick response. I determined that my 10 and 30 second times are simply docker and kubernetes default graceful termination timeouts. The following commands don't resolve things:

- `node app.js`
- `pm2 start --no-daemon app.js -n enketo`

Based on this [SO post](https://stackoverflow.com/a/58282598/443457), it looks like we may need to handle the signal manually. I'll try it out and hopefully submit a PR.

**Comment by jnm** [comment]
I don't see any reason why the Enketo `Dockerfile` shouldn't use `pm2-runtime`. Otherwise, every Enketo Docker container that doesn't have some custom override will go through this unnecessary sequence when stopping:
1. `TERM` to PID 1 (`pm2`) inside the container;
2. Wait in vain for 10 seconds;
3. Kill the container.

Right?

> Use pm2-runtime always under the assumption it wouldn't cause harm in cases where it's unnecessary

Where is it unnecessary? Or do you define unnecessary as being in a situation where no one cares about the 10-second delay? It seems to me that running a process as PID 1 inside a Docker container that does not handle `TERM` properly is fundamentally wrong—albeit not necessarily damaging.

Thanks

**Comment by bufke** [comment]
The [Dockerfile](https://github.com/enketo/enketo-express/blob/master/Dockerfile#L18) currently executes [start.sh](https://github.com/enketo/enketo-express/blob/master/setup/docker/start.sh) which itself then uses pm2.

I had a fear that changing start.sh could lead to some unpredictable change. I suppose only docker users are using this file and pm2 seems to recommend Docker users make use of pm2-runtime. So perhaps we should just change it? If you agree, then I can open a PR.

**Comment by jnm** [comment]
> I suppose only docker users are using this file

That was certainly the intent given that it's in the `setup/docker` directory (and I [remember](https://github.com/enketo/enketo-express/blob/1a5dc306cd1c741290fcd7b9973eb3bd1001cb40/setup/docker/run_enketo.bash) when it was written) :wink: but of course we could never say for sure.

Just for the heck of it, I ran `pm2-runtime` outside of Docker, and it seems totally fine. I'm sure there are some notable differences from `pm2 start --no-daemon` (like support for signal handling as PID 1!), but I don't think they will present an issue even if someone is using `setup/docker/start.sh` outside of Docker. `pm2-runtime` outside Docker responds the same way to `SIGTERM` as `pm2 start --no-daemon` does.

Please make the PR :+1:

**Comment by lognaturel** [comment]
So it's `pm2` running on PID1, not the triggering shell script? You're confident modifying the way the shell script is run (e.g. `CMD ["start.sh"]` to avoid `sh -c`) has no effect?

I've only quickly looked at `pm2-runtime` but it does seem appropriate. Does it actually fix the problem without a change to how the shell script is called?

**Comment by jnm** [comment]
Yes! It's a bit surprising, right? :smile: With the current
```
CMD ${ENKETO_SRC_DIR}/setup/docker/start.sh
```
…there's no intermediary `sh` process remaining; here's the output from `ps faux` on the host:
```
root      121165  0.0  0.0 710324  7908 ?        Sl   11:45   0:00 /usr/bin/containerd-shim-runc-v2 -namespace moby -id 5f3f5b6ef7b83b9ddde7ffe09fec81f7f696e826507f61891ef598d17428e582 -address /run/containerd/containerd.sock
root      121184  3.8  0.3 895764 47484 ?        Ssl  11:45   0:00  \_ node /usr/local/bin/pm2 start --no-daemon app.js -n enketo
root      121274  2.2  0.2 620340 40852 ?        Ssl  11:45   0:00      \_ node /srv/src/enketo_express/app.js
root      121295 11.3  0.5 666424 86496 ?        Sl   11:45   0:01          \_ node /srv/src/enketo_express/app.js
root      121296 11.3  0.5 662424 84452 ?        Sl   11:45   0:01          \_ node /srv/src/enketo_express/app.js
root      121297 11.5  0.5 663724 85360 ?        Sl   11:45   0:01          \_ node /srv/src/enketo_express/app.js
<snip>
```
I believe this is because the `node:14` base image has `ENTRYPOINT ["docker-entrypoint.sh"]` [in its `Dockerfile`](https://github.com/nodejs/docker-node/blob/550335de399159288f34e225802665d90a044790/14/buster/Dockerfile#L66), meaning that the `CMD` string in *our* `Dockerfile` is passed [as an argument](https://docs.docker.com/engine/reference/builder/#exec-form-entrypoint-example) to `docker-entrypoint.sh`, which itself is run directly (in "exec form"), not with `sh -c`. Honestly, I'm too lazy right now to decipher the shell incantations in [`docker-entrypoint.sh`](https://github.com/nodejs/docker-node/blob/550335de399159288f34e225802665d90a044790/14/buster/docker-entrypoint.sh), but I can say empirically that it ends up `exec`ing our script and thus replacing itself with our script's interpreter, which in turn `exec`s `pm2`, ultimately leading to `pm2` being PID 1 in the container as we can observe.
```
john@world$ cat start.sh 
#!/bin/sh -x
exec tail -f /dev/null

john@world$ cat docker-entrypoint.sh 
#!/bin/sh
set -e

# Run command with node if the first argument contains a "-" or is not a system command. The last
# part inside the "{}" is a workaround for the following bug in ash/dash:
# https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=874264
if [ "${1#-}" != "${1}" ] || [ -z "$(command -v "${1}")" ] || { [ -f "${1}" ] && ! [ -x "${1}" ]; }; then
  set -- node "$@"
fi

exec "$@"

john@world$ sh -x docker-entrypoint.sh ./start.sh 
+ set -e
+ [ ./start.sh != ./start.sh ]
+ command -v ./start.sh
+ [ -z ./start.sh ]
+ [ -f ./start.sh ]
+ [ -x ./start.sh ]
+ exec ./start.sh
+ exec tail -f /dev/null
```

**Comment by jnm** [comment]
@lognaturel, @bufke, my analysis [above](https://github.com/enketo/enketo-express/issues/531#issuecomment-1465316065) was wrong. When the shell form of `CMD` is used in a `Dockerfile`, it overrides `ENTRYPOINT`; the `CMD` string is *not* sent as an argument to `ENTRYPOINT`:
```
john@world:/tmp/ilovedocker$ cat > start.sh
#!/bin/sh -x
exec tail -f /dev/null

john@world:/tmp/ilovedocker$ cat > Dockerfile
FROM node:14
CMD /ilovedocker/start.sh

john@world:/tmp/ilovedocker$ docker build -t node14-with-cmd .
<snip>
Successfully tagged node14-with-cmd:latest

john@world:/tmp/ilovedocker$ docker run --rm -it -v /tmp/ilovedocker:/ilovedocker --name test-container node14-with-cmd
+ exec tail -f /dev/null

<in another terminal>
john@eight4eight:/tmp/ilovedocker$ docker exec -it test-container ps faux
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root          15  0.0  0.0   7640  2688 pts/1    Rs+  21:42   0:00 ps faux
root           1  0.0  0.0   2388  1408 pts/0    Ss+  21:42   0:00 /bin/sh -c /i
root           8  0.0  0.0   2328  1280 pts/0    S+   21:42   0:00 tail -f /dev/
```

As a result, `pm2-runtime` is not running as PID 1, even after #533. I'm not sure what mistake I made while testing it before, but I'll submit a PR to correct the problem.

**Comment by lognaturel** [comment]
Aha, great!

**Comment by lognaturel** [comment]
Latest change reverted with explanation at https://github.com/enketo/enketo-express/pull/582#issuecomment-1687080687
