### ISSUE TITLE
Switch from applicationCache to service workers

### ISSUE THREAD

**Issue by enketo-issue-mover** [enketo/enketo-express#55]
_From @MartijnR on February 3, 2016 21:59_

applicationCache is being deprecated

https://html.spec.whatwg.org/multipage/browsers.html#offline

Too early at the moment. http://caniuse.com/#feat=serviceworkers

_Copied from original issue: kobotoolbox/enketo-express#401_

**Comment by enketo-issue-mover** [comment]
_From @MartijnR on February 16, 2016 20:32_

to fix afterwards:
- [ ] remove awkward method of passing submission parameter to offline view

**Comment by enketo-issue-mover** [comment]
_From @MartijnR on August 17, 2018 23:54_

First thing to check is the 24 hour thing, as we need users to be able to stay disconnected for much longer.

https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API

**Comment by MartijnR** [comment]
This is becoming urgent. 
```
enketo-webform-bundle.js:107875 [Deprecation] Application Cache API use is deprecated and will be removed in M82, around April 2020. See https://www.chromestatus.com/features/6192449487634432 for more details.
```

**Comment by chrismclarke** [comment]
In case it's of interest, google does have a rough tool aimed to help migrate from appcache to service workers: https://github.com/GoogleChromeLabs/sw-appcache-behavior

It claims to be work in progress (although fairly inactive and so for a complex setup may not work, but could be worth a try.

**Comment by MartijnR** [comment]
Thank you. I wasn't aware of that tool!

**Comment by MartijnR** [comment]
This version (major version perhaps) should also officially remove IE11 support #129

**Comment by MartijnR** [comment]
Would be useful to use the form definition to determine which languages to cache. This would enable proper UI language switching in the future. 

Alternatively, we could dynamically add any additional languages the user switches to while online.

**Comment by MartijnR** [comment]
future:

* form cache for form itself + media/data resources + translations (and getting rid of \#urls)
*

**Comment by MartijnR** [comment]
Note: 

The explicit list of resources may not serve much of a purpose (vs. dynamically caching whatever is requested in the scope of the service worker (/x/path/to/resource). But we need to update the (byte value) of the service worker if any resource changes, so we'll have to go through all resources anyway.

However, it's worth considering just incrementing the service worker (version) whenever, Enketo is restarted or gets a new git tag or something. The only issue with that would be for Enketo developers (but developer tools has a setting to always update).
