### ISSUE TITLE
Sync Form language with UI language (if match found)

### ISSUE THREAD

**Issue by enketo-issue-mover** [enketo/enketo-express#57]
_From @MartijnR on June 23, 2016 22:13_

Will require recommended language name with iso code such as `English (en)`, `Arabic (ar)` as agreed in ODK Dev forum: https://groups.google.com/forum/#!searchin/opendatakit-developers/language$20names$20proposal%7Csort:relevance/opendatakit-developers/ZLDJanOCudE/T7yTrDMYVAsJ

See "Tip: Prepare for the Future" in this post: http://blog.enketo.org/advanced-language/

Algorithm:

_Copied from original issue: kobotoolbox/enketo-express#526_

**Comment by enketo-issue-mover** [comment]
_From @smusula on July 13, 2016 11:26_

How is this expected to work?

Will it possible for someone to have a url like [https://enketo.ona.io/::YYGk?language=Amharic](https://enketo.ona.io/::YYGk?language=Amharic)? - where Amharic is one of the languages defined in the XLSForm.

**Comment by enketo-issue-mover** [comment]
_From @MartijnR on July 13, 2016 15:10_

It's not determined yet how this will work. Your suggestion is an option but it would use the official 2-character language code (IANA) instead. I think we should at least include:
1. If browser locale is available as form language load that form language as default (ignoring any defined XForm default?).
~~2. If user switches form language, the UI language should also be switched if that language is available.~~

**Comment by enketo-issue-mover** [comment]
_From @smusula on July 26, 2016 9:29_

Thanks for the feedback

**Comment by enketo-issue-mover** [comment]
_From @MartijnR on October 11, 2016 18:49_

point 1 could be taken care of by e.g https://github.com/kobotoolbox/enketo-express/commit/57dd427d4f52115ca28ffb2d3ebbd89c72bf6926 (note this is not in master and this branch will not be merged in master)

**Comment by enketo-issue-mover** [comment]
_From @MartijnR on March 27, 2017 19:58_

This issue has been reduced to only solve point 1. 

Though OC would need point 2 as well. Maybe as an online-only feature, or a limited set of languages that can be set in config.json since most small implementations may not need all languages. Problem is that lots of strings are added in jade/pug.

**Comment by enketo-issue-mover** [comment]
This issue was moved to OpenClinica/enketo-express-oc#95

**Comment by MartijnR** [comment]
After #55:

* [ ] add a little initialization function in offline-capable views that looks at form language selector and loads (and therefore caches) the missing UI translations, upon load so that they're available offline (pretty cool!)

**Comment by MartijnR** [comment]
http://localhost:8005/cVDzvcgB

**Comment by MartijnR** [comment]
Scenarios to test. Please comment!

https://docs.google.com/spreadsheets/d/1CigMLAQewcXi-OJJHi_JQQ-fJXOam99livM0oYrtbkk/edit#gid=0
