### ISSUE TITLE
URL validator doesn't accept host-only urls apart from localhost

### ISSUE THREAD

**Issue by enketo-issue-mover** [enketo/enketo-express#58]
_From @MartijnR on May 14, 2018 16:4_

E.g. `http://d4h:8080` is not accepted. I think this is a bug.

_Copied from original issue: kobotoolbox/enketo-express#1015_

**Comment by enketo-issue-mover** [comment]
_From @MartijnR on September 10, 2018 22:57_

may have been fixed. check

**Comment by MartijnR** [comment]
yes is fixed (API accepts)
