### ISSUE TITLE
Production install fails

### ISSUE THREAD

**Issue by s13g3lb4um** [enketo/enketo-express#70]
I tried to install enketo on production environment, i follow the next [Install Instructions](https://blog.enketo.org/install-enketo-production-ubuntu/) but in the step 6 Configuration the services `redis-server@enketo-main.service` and `redis-server@enketo-cache.service` don't start
this is the exit error on ` systemctl status redis-enketo-cache.service`

`Nov 16 16:26:55 Enketo systemd[1]: redis-enketo-cache.service: Control process exited, code=exited status=203
Nov 16 16:26:55 Enketo systemd[1]: Failed to start Redis In-Memory Data Store.
Nov 16 16:26:55 Enketo systemd[1]: redis-enketo-cache.service: Unit entered failed state.
Nov 16 16:26:55 Enketo systemd[1]: redis-enketo-cache.service: Failed with result 'exit-code'.
Nov 16 16:26:55 Enketo systemd[1]: redis-enketo-cache.service: Service hold-off time over, 
scheduling restart.
Nov 16 16:26:55 Enketo systemd[1]: Stopped Redis In-Memory Data Store.
Nov 16 16:26:55 Enketo systemd[1]: redis-enketo-cache.service: Start request repeated too quickly.
Nov 16 16:26:55 Enketo systemd[1]: Failed to start Redis In-Memory Data Store.
Nov 16 16:26:55 Enketo systemd[1]: redis-enketo-cache.service: Unit entered failed state.
Nov 16 16:26:55 Enketo systemd[1]: redis-enketo-cache.service: Failed with result 'start-limit-hit'.
`

The Journalctl says this:

`Unit redis-enketo-cache.service has begun starting up.
Nov 16 20:56:08 Enketo systemd[21046]: redis-enketo-cache.service: Failed at step EXEC spawning /usr/local/bin/redis-server-enketo-cache: No such file`

exists any way to create this file?

**Comment by MartijnR** [comment]
Not sure where that redis-server-enketo-cache reference comes from. Sounds like an old thing. Did you start with a fresh server and a recent Enketo Express version?

The redis config files are here: https://github.com/kobotoolbox/enketo-express/tree/master/setup/redis

(I am about to go on leave, so I won't be able to help for a while). 

If you find any error in the blog post, please let me know!

**Comment by s13g3lb4um** [comment]
i cloned the repository today 

the content of redis-enketo-main.service is this: 

`[Unit]
Description=Redis In-Memory Data Store
After=network.target

[Service]
Type=forking
User=redis
Group=redis
ExecStart=/usr/local/bin/redis-enketo-main /etc/redis/redis-enketo-main.conf
ExecStop=/usr/local/bin/redis-cli shutdown
Restart=always

[Install]
WantedBy=multi-user.target
`

the file `/usr/local/bin/redis-enketo-main` don't exits

**Comment by saif2khan** [comment]
Facing the same problem. Did it get resolved?
