### ISSUE TITLE
Docker build fails - missing modules?

### ISSUE THREAD

**Issue by dmenne** [enketo/enketo-express#78]
Trying to build with docker-compose on Ubuntu Server. Restarts never-ending, most suspicious entries look like:

``` 
enketo_express_1  | >> Local Npm module "grunt-concurrent" not found. Is it installed?
enketo_express_1  | >> Local Npm module "grunt-contrib-watch" not found. Is it installed?
enketo_express_1  | >> Local Npm module "grunt-eslint" not found. Is it installed?
enketo_express_1  | >> Local Npm module "grunt-jsbeautifier" not found. Is it installed?
enketo_express_1  | >> Local Npm module "grunt-karma" not found. Is it installed?
enketo_express_1  | >> Local Npm module "grunt-mocha-test" not found. Is it installed?
enketo_express_1  | >> Local Npm module "grunt-nodemon" not found. Is it installed?

```

**Comment by MartijnR** [comment]
I don't know anything about docker, but just wanted to let you know that these warnings can be ignored. These modules are not used in production mode.

Hope somebody else can help.

**Comment by dmenne** [comment]
Thanks, I will have to check elsewere what's the source.

**Comment by awemulya** [comment]
@dmenne  please install from source https://github.com/enketo/enketo-express follow the documentation at README. I have just setup from source its working.

**Comment by dmenne** [comment]
Thanks, @awemulya, I always install from source and end up with "bad gateway 502". I cannot use port 80 on my machine, so I did

  ports:
    - "8000:80"

in setup/docker/docker-compose.yml

Have you been able to run on a different port?

**Comment by MartijnR** [comment]
I am assuming this is fixed in later docker setup. Otherwise reopen
