### ISSUE TITLE
enketo-core src/sass/core folder is missing during npm install

### ISSUE THREAD

**Issue by MartijnR** [enketo/enketo-express#86]
Very mysterious. Looks like npm bug because there is no .gitignore file in enketo-core.

```
node -v && npm -v
v8.15.0
6.8.0
```

**Comment by MartijnR** [comment]
downgrading to npm 6.7 is a solution so yes likely a bug in npm 6.8.0.

`npm install -g npm@6.7` or `sudo npm install -g npm@6.7`

**Comment by MartijnR** [comment]
Yep! https://npm.community/t/npm-pack-leaving-out-files-6-8-0-only/5382/11

**Comment by MartijnR** [comment]
should be resolved in npm 6.9.0

**Comment by s13g3lb4um** [comment]
I have this versions 
![imagen](https://user-images.githubusercontent.com/12554805/59138223-864c1480-8951-11e9-8780-1cc178280335.png)
and I have the same problem...

**Comment by MartijnR** [comment]
Thanks for reporting! Enketo-core is a dependency listed in package.json, so it is installed as part of `npm install --production`. I'll check it out to see if I messed something up!

**Comment by MartijnR** [comment]
All seems to be working for me. It may have been a temporary npm problem. Could you try re-installing the npm dependencies, like this:

1. `cd ~/enketo-express`
2. `rm -R node_modules`
3. `npm install --production`
