### ISSUE TITLE
Pre-fill form fields using Enketo Express

### ISSUE THREAD

**Issue by Y2KWebs** [enketo/enketo-express#89]
Hello

I found and article by ona that describes this method to pre-fill fields in a enketo from:

https://enketo.ona.io/_/?d[/xpath/to/field_name]=<prefill-value>&d[/xpath/to/other_field_name]=<prefill-value>#ABC2

However I'm unable to replicate this in my self hosted kobotollbox enketo form

Does this only work for Ona?

Thanks!

**Comment by MartijnR** [comment]
Hi,

The feature works across all Enketo Express installations, but only for certain views. Do not attempt to manually craft the webform URLs, but use the API instead to do this for you. Have a look at those API endpoints (and associated views) that support the `defaults` parameter. Good luck!

**Comment by MartijnR** [comment]
Sorry, forgot the link: https://apidocs.enketo.org/v2
