### ISSUE TITLE
Editing a data submission with a repeat calculation fails

### ISSUE THREAD

**Issue by smusula** [enketo/enketo-express#95]
One is able to submit a form with a repeat calculation successfully,  however, when editing the submitted instance the following error message is displayed:

![error_editing](https://user-images.githubusercontent.com/4832172/57626558-66b20e00-7596-11e9-8a7f-73a18b07c3a3.PNG)

**Steps to recreate:**
- Upload [this XLSForm](https://docs.google.com/spreadsheets/d/1p9XF7ouX5CJHVADvssXBEQG6loA6drC2SUPG_R8i4zI/edit?usp=sharing) to your Kobo account, complete it and submit  (problematic section **row 16, column J**)
- Then, go to the edit link of the submitted form, you will receive the error message

Platforms: https://kobo.unhcr.org, https://kobo.humanitarianresponse.info
XLSForm used:  https://docs.google.com/spreadsheets/d/1p9XF7ouX5CJHVADvssXBEQG6loA6drC2SUPG_R8i4zI/edit?usp=sharing
Enketo form: https://enketo.unhcr.org/x/#Pqen2jMb

**Comment by ChloeLaborde** [comment]
Hey !
I am facing the same issue on different forms.... Is there any timeline on when this issue will be fixed? need to move forward on my project ....

**Comment by MartijnR** [comment]
I actually wonder if this is resolved with a recent version of pyxform (for newly uploaded forms). If anybody is able to test this that would be great.

Will still leave this open to be fixed for old forms though. No ETA, sorry.

**Comment by ChloeLaborde** [comment]
Hi everyone,

Thank you very much for the answer @MartijnR
Indeed, I tested it and this issue is fix ! First I tried with a new form and new submissions. But also tried with old ones and it's fix too :) 

All the best,
Chloé

**Comment by MartijnR** [comment]
Oh wow, that's great! Thanks for checking. So I've learned that sometimes, just sitting on an issue works! :)
